from django.urls import path

from accounts.views import (
    AudespCredentialSettingsFormView,
    AudespCredentialSettingsListView,
    FolderManagerCreateView,
    FolderManagersDetailView,
    FolderManagersListView,
    InterestedUserOptionsView,
    OrganizationAccountantCreateView,
    OrganizationAccountantsDetailView,
    OrganizationAccountantsListView,
    OrganizationCommitteeCreateView,
    OrganizationCommitteesDetailView,
    OrganizationCommitteesListView,
    OrganizationDocumentCreateView,
    OrganizationDocumentDeleteView,
    OrganizationDocumentListView,
    OrganizationDocumentToggleVisibilityView,
    OrganizationDocumentUpdateView,
    get_committee_members,
    read_notification_view,
    toggle_audesp_credential_status,
    toggle_folder_manager_status,
    toggle_organization_accountant_status,
    toggle_organization_committee_status,
    user_unread_notifications,
)

urlpatterns = [
    # API Endpoints
    path(
        "interested-users/options/",
        InterestedUserOptionsView.as_view(),
        name="interested-user-options",
    ),
    path(
        "get-committee-members/",
        get_committee_members,
        name="get-committee-members",
    ),
    # Folder Managers Views
    path(
        "notifications/",
        user_unread_notifications,
        name="user-notifications",
    ),
    path(
        "notifications/<uuid:pk>/read",
        read_notification_view,
        name="user-read-notifications",
    ),
    path(
        "folder-managers/",
        FolderManagersListView.as_view(),
        name="folder-managers-list",
    ),
    path(
        "folder-managers/create/",
        FolderManagerCreateView.as_view(),
        name="folder-managers-create",
    ),
    path(
        "folder-managers/<int:pk>/",
        FolderManagersDetailView.as_view(),
        name="folder-managers-detail",
    ),
    path(
        "folder-managers/<int:pk>/toggle-status/",
        toggle_folder_manager_status,
        name="folder-managers-toggle-status",
    ),
    # Organization Accountant Views
    path(
        "organization-accountants/",
        OrganizationAccountantsListView.as_view(),
        name="organization-accountants-list",
    ),
    path(
        "organization-accountants/create/",
        OrganizationAccountantCreateView.as_view(),
        name="organization-accountants-create",
    ),
    path(
        "organization-accountants/<int:pk>/",
        OrganizationAccountantsDetailView.as_view(),
        name="organization-accountants-detail",
    ),
    path(
        "organization-accountants/<int:pk>/toggle-status/",
        toggle_organization_accountant_status,
        name="organization-accountants-toggle-status",
    ),
    # Organization Committee Views
    path(
        "organization-committees/",
        OrganizationCommitteesListView.as_view(),
        name="organization-committees-list",
    ),
    path(
        "organization-committees/create/",
        OrganizationCommitteeCreateView.as_view(),
        name="organization-committees-create",
    ),
    path(
        "organization-committees/<int:pk>/",
        OrganizationCommitteesDetailView.as_view(),
        name="organization-committees-detail",
    ),
    path(
        "organization-committees/<int:pk>/toggle-status/",
        toggle_organization_committee_status,
        name="organization-committees-toggle-status",
    ),
    # Organization Documents
    path(
        "documents/",
        OrganizationDocumentListView.as_view(),
        name="documents-list",
    ),
    path(
        "documents/add/",
        OrganizationDocumentCreateView.as_view(),
        name="documents-add",
    ),
    path(
        "documents/<uuid:pk>/edit/",
        OrganizationDocumentUpdateView.as_view(),
        name="documents-edit",
    ),
    path(
        "documents/<uuid:pk>/delete/",
        OrganizationDocumentDeleteView.as_view(),
        name="documents-delete",
    ),
    path(
        "documents/<uuid:pk>/toggle-visibility/",
        OrganizationDocumentToggleVisibilityView.as_view(),
        name="documents-toggle-visibility",
    ),
    # AUDESP credential settings (city-hall-scoped, see audesp/models.py's
    # AudespCredential docstring)
    path(
        "audesp/",
        AudespCredentialSettingsListView.as_view(),
        name="audesp-credentials-list",
    ),
    path(
        "audesp/<str:environment>/",
        AudespCredentialSettingsFormView.as_view(),
        name="audesp-credentials-form",
    ),
    path(
        "audesp/<str:environment>/toggle-status/",
        toggle_audesp_credential_status,
        name="audesp-credentials-toggle-status",
    ),
]
