# [START gaeflex_py_django_app_yaml]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT core.wsgi

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

beta_settings:
    cloud_sql_instances: sitts-project:REGION:postgres

# [END gaeflex_py_django_app_yaml]
