# [START gaeflex_py_django_app_yaml]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT core.wsgi

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

beta_settings:
    cloud_sql_instances: sitts-project:REGION:postgres

vpc_access_connector:
    name: projects/sitts-project/locations/REGION/connectors/redis-connector

env_variables:
    REDIS_HOST: '10.232.60.11'
    REDIS_PORT: '6379'

# [END gaeflex_py_django_app_yaml]
