# Generated by Django 5.1.4 on 2025-02-16 13:06

import uuid

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accountability", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        max_length=128, verbose_name="Nome do Banco"
                    ),
                ),
                ("bank_id", models.IntegerField(verbose_name="Id do Banco")),
                (
                    "account",
                    models.CharField(
                        max_length=16, verbose_name="Número da Conta"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "conta corrente"),
                            ("INVESTING", "investimento"),
                        ],
                        default="CHECKING",
                        max_length=9,
                        verbose_name="Tipo da Conta",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Agência",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Saldo Atual",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("MUNICIPAL", "Municipal"),
                            ("FEDERAL", "Federal"),
                            ("STATE", "Estadual"),
                            (
                                "COUNTERPART_PARTNER",
                                "Contrapartida de parceiro",
                            ),
                            ("PRIVATE_SPONSOR", "Patrocinador privado"),
                        ],
                        default="MUNICIPAL",
                        max_length=19,
                        verbose_name="Origem da Fonte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
            },
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo no Dia Inicial",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo no Dia Final",
                    ),
                ),
                (
                    "reference_month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "reference_year",
                    models.IntegerField(default=0, verbose_name="Ano"),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="bank.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrato Bancário",
                "verbose_name_plural": "Extratos Bancários",
            },
        ),
        migrations.CreateModel(
            name="HistoricalBankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        max_length=128, verbose_name="Nome do Banco"
                    ),
                ),
                ("bank_id", models.IntegerField(verbose_name="Id do Banco")),
                (
                    "account",
                    models.CharField(
                        max_length=16, verbose_name="Número da Conta"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "conta corrente"),
                            ("INVESTING", "investimento"),
                        ],
                        default="CHECKING",
                        max_length=9,
                        verbose_name="Tipo da Conta",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Agência",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Saldo Atual",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("MUNICIPAL", "Municipal"),
                            ("FEDERAL", "Federal"),
                            ("STATE", "Estadual"),
                            (
                                "COUNTERPART_PARTNER",
                                "Contrapartida de parceiro",
                            ),
                            ("PRIVATE_SPONSOR", "Patrocinador privado"),
                        ],
                        default="MUNICIPAL",
                        max_length=19,
                        verbose_name="Origem da Fonte",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Conta Bancária",
                "verbose_name_plural": "historical Contas Bancárias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo no Dia Inicial",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo no Dia Final",
                    ),
                ),
                (
                    "reference_month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "reference_year",
                    models.IntegerField(default=0, verbose_name="Ano"),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bank.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Extrato Bancário",
                "verbose_name_plural": "historical Extratos Bancários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor da Transação",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da Transação")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "débito"),
                            ("CREDIT", "crédito"),
                            ("INT", "juros"),
                            ("DIV", "dividendos"),
                            ("FEE", "taxa"),
                            ("SRVCHG", "taxa de serviço"),
                            ("DEP", "depósito"),
                            ("ATM", "caixa eletrônico"),
                            ("POS", "ponto de venda"),
                            ("XFER", "transferência entre contas"),
                            ("CHECK", "cheque"),
                            ("PAYMENT", "fatura ou débito"),
                            ("CASH", "saque"),
                            ("DIRECTDEP", "depósito direto"),
                            ("DIRECTDEBIT", "débito automático"),
                            ("REPEATPMT", "pagamento recorrente"),
                            ("INCOME", "retorno de investimentos"),
                            ("OTHER", "outros"),
                        ],
                        default="OTHER",
                        max_length=32,
                        verbose_name="Tipo da Transação",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Id da Transação",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Notas Adicionais (opcional)",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bank.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
                (
                    "destination_source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.resourcesource",
                        verbose_name="Fonte Recurso Destino",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.expense",
                        verbose_name="Despesa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.resourcesource",
                        verbose_name="Fonte Recurso Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Movimentação Bancária",
                "verbose_name_plural": "historical Movimentações Bancárias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor da Transação",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da Transação")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "débito"),
                            ("CREDIT", "crédito"),
                            ("INT", "juros"),
                            ("DIV", "dividendos"),
                            ("FEE", "taxa"),
                            ("SRVCHG", "taxa de serviço"),
                            ("DEP", "depósito"),
                            ("ATM", "caixa eletrônico"),
                            ("POS", "ponto de venda"),
                            ("XFER", "transferência entre contas"),
                            ("CHECK", "cheque"),
                            ("PAYMENT", "fatura ou débito"),
                            ("CASH", "saque"),
                            ("DIRECTDEP", "depósito direto"),
                            ("DIRECTDEBIT", "débito automático"),
                            ("REPEATPMT", "pagamento recorrente"),
                            ("INCOME", "retorno de investimentos"),
                            ("OTHER", "outros"),
                        ],
                        default="OTHER",
                        max_length=32,
                        verbose_name="Tipo da Transação",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Id da Transação",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Notas Adicionais (opcional)",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bank.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
                (
                    "destination_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_destinations",
                        to="accountability.resourcesource",
                        verbose_name="Fonte Recurso Destino",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="accountability.expense",
                        verbose_name="Despesa",
                    ),
                ),
                (
                    "origin_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_origins",
                        to="accountability.resourcesource",
                        verbose_name="Fonte Recurso Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação Bancária",
                "verbose_name_plural": "Movimentações Bancárias",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("transaction_id__isnull", False),
                        ),
                        fields=("transaction_id",),
                        name="unique__transaction_id",
                    )
                ],
            },
        ),
    ]
