# Generated by Django 6.0.5 on 2026-05-14 00:14

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountability', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank_name', models.CharField(help_text='Name of the bank or financial institution', max_length=128, verbose_name='Nome do Banco')),
                ('bank_id', models.IntegerField(help_text='Bank identification number', verbose_name='Id do Banco')),
                ('account', models.CharField(help_text='Bank account number', max_length=16, verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('INVESTING', 'Investimento')], default='CHECKING', help_text='Type of bank account (checking or investment)', max_length=9, verbose_name='Tipo da Conta')),
                ('agency', models.CharField(blank=True, help_text='Bank branch/agency number', max_length=128, null=True, verbose_name='Agência')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the moment the account was registered. The current balance is derived from this anchor plus all transactions.', max_digits=12, verbose_name='Saldo de Abertura')),
                ('origin', models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('FEDERAL', 'Federal'), ('STATE', 'Estadual'), ('COUNTERPART_PARTNER', 'Contrapartida de parceiro'), ('PRIVATE_SPONSOR', 'Patrocinador privado')], default='MUNICIPAL', help_text='Source of funds for this account', max_length=19, verbose_name='Origem da Fonte')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, help_text='The balance at the start of the statement period', max_digits=12, null=True, verbose_name='Saldo no Dia Inicial')),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='The balance at the end of the statement period', max_digits=12, verbose_name='Saldo no Dia Final')),
                ('reference_day', models.IntegerField(blank=True, help_text='The day this statement refers to', null=True, verbose_name='Dia de Referência')),
                ('reference_month', models.IntegerField(choices=[(1, 'janeiro'), (2, 'fevereiro'), (3, 'março'), (4, 'abril'), (5, 'maio'), (6, 'junho'), (7, 'julho'), (8, 'agosto'), (9, 'setembro'), (10, 'outubro'), (11, 'novembro'), (12, 'dezembro')], default=1, help_text='The month this statement refers to', verbose_name='Mês')),
                ('reference_year', models.IntegerField(default=0, help_text='The year this statement refers to', verbose_name='Ano')),
                ('bank_account', models.ForeignKey(help_text='The bank account this statement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='bank.bankaccount', verbose_name='Conta Bancária')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank_name', models.CharField(help_text='Name of the bank or financial institution', max_length=128, verbose_name='Nome do Banco')),
                ('bank_id', models.IntegerField(help_text='Bank identification number', verbose_name='Id do Banco')),
                ('account', models.CharField(help_text='Bank account number', max_length=16, verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('INVESTING', 'Investimento')], default='CHECKING', help_text='Type of bank account (checking or investment)', max_length=9, verbose_name='Tipo da Conta')),
                ('agency', models.CharField(blank=True, help_text='Bank branch/agency number', max_length=128, null=True, verbose_name='Agência')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the moment the account was registered. The current balance is derived from this anchor plus all transactions.', max_digits=12, verbose_name='Saldo de Abertura')),
                ('origin', models.CharField(choices=[('MUNICIPAL', 'Municipal'), ('FEDERAL', 'Federal'), ('STATE', 'Estadual'), ('COUNTERPART_PARTNER', 'Contrapartida de parceiro'), ('PRIVATE_SPONSOR', 'Patrocinador privado')], default='MUNICIPAL', help_text='Source of funds for this account', max_length=19, verbose_name='Origem da Fonte')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'historical Conta Bancária',
                'verbose_name_plural': 'historical Contas Bancárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankStatement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, help_text='The balance at the start of the statement period', max_digits=12, null=True, verbose_name='Saldo no Dia Inicial')),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='The balance at the end of the statement period', max_digits=12, verbose_name='Saldo no Dia Final')),
                ('reference_day', models.IntegerField(blank=True, help_text='The day this statement refers to', null=True, verbose_name='Dia de Referência')),
                ('reference_month', models.IntegerField(choices=[(1, 'janeiro'), (2, 'fevereiro'), (3, 'março'), (4, 'abril'), (5, 'maio'), (6, 'junho'), (7, 'julho'), (8, 'agosto'), (9, 'setembro'), (10, 'outubro'), (11, 'novembro'), (12, 'dezembro')], default=1, help_text='The month this statement refers to', verbose_name='Mês')),
                ('reference_year', models.IntegerField(default=0, help_text='The year this statement refers to', verbose_name='Ano')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, help_text='The bank account this statement belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank.bankaccount', verbose_name='Conta Bancária')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'historical Extrato Bancário',
                'verbose_name_plural': 'historical Extratos Bancários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction (positive for credits, negative for debits)', max_digits=12, verbose_name='Valor da Transação')),
                ('date', models.DateField(help_text='The date when the transaction occurred', verbose_name='Data da Transação')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'débito'), ('CREDIT', 'crédito'), ('INT', 'juros'), ('DIV', 'dividendos'), ('FEE', 'taxa'), ('SRVCHG', 'taxa de serviço'), ('DEP', 'depósito'), ('ATM', 'caixa eletrônico'), ('POS', 'ponto de venda'), ('XFER', 'transferência entre contas'), ('CHECK', 'cheque'), ('PAYMENT', 'fatura ou débito'), ('CASH', 'saque'), ('DIRECTDEP', 'depósito direto'), ('DIRECTDEBIT', 'débito automático'), ('REPEATPMT', 'pagamento recorrente'), ('INCOME', 'retorno de investimentos'), ('OTHER', 'outros')], default='OTHER', help_text='The type of transaction (e.g., credit, debit, transfer)', max_length=32, verbose_name='Tipo da Transação')),
                ('transaction_number', models.CharField(blank=True, help_text='Unique identifier for the transaction from the bank', max_length=32, null=True, verbose_name='Id da Transação')),
                ('name', models.CharField(blank=True, help_text='Description or name of the transaction', max_length=128, null=True, verbose_name='Nome')),
                ('memo', models.CharField(blank=True, help_text='Additional notes or comments about the transaction', max_length=256, null=True, verbose_name='Notas Adicionais (opcional)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, help_text='The bank account this transaction belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank.bankaccount', verbose_name='Conta Bancária')),
                ('expense', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated expense record if this is an expense transaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.expense', verbose_name='Despesa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization')),
                ('revenue', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated revenue record if this is a revenue transaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.revenue', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'historical Movimentação Bancária',
                'verbose_name_plural': 'historical Movimentações Bancárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction (positive for credits, negative for debits)', max_digits=12, verbose_name='Valor da Transação')),
                ('date', models.DateField(help_text='The date when the transaction occurred', verbose_name='Data da Transação')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'débito'), ('CREDIT', 'crédito'), ('INT', 'juros'), ('DIV', 'dividendos'), ('FEE', 'taxa'), ('SRVCHG', 'taxa de serviço'), ('DEP', 'depósito'), ('ATM', 'caixa eletrônico'), ('POS', 'ponto de venda'), ('XFER', 'transferência entre contas'), ('CHECK', 'cheque'), ('PAYMENT', 'fatura ou débito'), ('CASH', 'saque'), ('DIRECTDEP', 'depósito direto'), ('DIRECTDEBIT', 'débito automático'), ('REPEATPMT', 'pagamento recorrente'), ('INCOME', 'retorno de investimentos'), ('OTHER', 'outros')], default='OTHER', help_text='The type of transaction (e.g., credit, debit, transfer)', max_length=32, verbose_name='Tipo da Transação')),
                ('transaction_number', models.CharField(blank=True, help_text='Unique identifier for the transaction from the bank', max_length=32, null=True, verbose_name='Id da Transação')),
                ('name', models.CharField(blank=True, help_text='Description or name of the transaction', max_length=128, null=True, verbose_name='Nome')),
                ('memo', models.CharField(blank=True, help_text='Additional notes or comments about the transaction', max_length=256, null=True, verbose_name='Notas Adicionais (opcional)')),
                ('bank_account', models.ForeignKey(help_text='The bank account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.bankaccount', verbose_name='Conta Bancária')),
                ('expense', models.ForeignKey(blank=True, help_text='Associated expense record if this is an expense transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accountability.expense', verbose_name='Despesa')),
                ('expenses', models.ManyToManyField(help_text='Multiple expenses associated with this transaction', related_name='bank_transactions', to='accountability.expense', verbose_name='Despesas')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
                ('revenue', models.ForeignKey(blank=True, help_text='Associated revenue record if this is a revenue transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accountability.revenue', verbose_name='Receita')),
                ('revenues', models.ManyToManyField(help_text='Multiple revenues associated with this transaction', related_name='bank_transactions', to='accountability.revenue', verbose_name='Receitas')),
            ],
            options={
                'verbose_name': 'Movimentação Bancária',
                'verbose_name_plural': 'Movimentações Bancárias',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_name', 'account'], name='bank_bankac_bank_na_12c426_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_type'], name='bank_bankac_account_ed7b30_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['origin'], name='bank_bankac_origin_06e584_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'bank_name', 'account', 'account_type'), name='unique_bank_account_per_organization'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account', 'reference_month', 'reference_year'], name='bank_bankst_bank_ac_83b054_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['reference_month', 'reference_year'], name='bank_bankst_referen_7e1081_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('bank_account', 'reference_month', 'reference_year', 'reference_day'), name='unique_bank_statement_per_month_year'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_account', 'date'], name='bank_transa_bank_ac_34371a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'date'], name='bank_transa_transac_5a1cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='bank_transa_transac_365a0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('transaction_number', 'memo', 'bank_account'), name='unique_transaction_number_per_bank_account'),
        ),
    ]
