# Generated by Django 5.1.6 on 2025-02-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0002_initial"),
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="unique__transaction_id",
        ),
        migrations.RenameField(
            model_name="historicaltransaction",
            old_name="transaction_id",
            new_name="transaction_number",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_id",
            new_name="transaction_number",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("transaction_number__isnull", False)
                ),
                fields=("transaction_number",),
                name="unique__transaction_number",
            ),
        ),
    ]
