# Generated by Django 5.1.4 on 2025-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("CHECKING", "conta corrente"), ("INVESTING", "investimento")],
                default="CHECKING",
                max_length=9,
                verbose_name="Tipo da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("CHECKING", "conta corrente"), ("INVESTING", "investimento")],
                default="CHECKING",
                max_length=9,
                verbose_name="Tipo da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Id da Transação"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Id da Transação"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id__isnull", True)),
                fields=("transaction_id",),
                name="unique__transaction_id",
            ),
        ),
    ]
