# Generated by Django 5.1.4 on 2025-01-15 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
        ("contracts", "0007_alter_contractitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Account",
            new_name="BankAccount",
        ),
        migrations.RenameModel(
            old_name="HistoricalAccount",
            new_name="HistoricalBankAccount",
        ),
        migrations.RenameField(
            model_name="bankstatement",
            old_name="account",
            new_name="bank_account",
        ),
        migrations.RenameField(
            model_name="historicalbankstatement",
            old_name="account",
            new_name="bank_account",
        ),
    ]
