# Generated by Django 5.1.4 on 2025-02-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0004_expense_due_date_historicalexpense_due_date"),
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransaction",
            name="destination_source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.resourcesource",
                verbose_name="Fonte Recurso Destino",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransaction",
            name="origin_source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.resourcesource",
                verbose_name="Fonte Recurso Origem",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="destination_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_destinations",
                to="accountability.resourcesource",
                verbose_name="Fonte Recurso Destino",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="origin_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_origins",
                to="accountability.resourcesource",
                verbose_name="Fonte Recurso Origem",
            ),
        ),
    ]
