# Generated by Django 5.1.4 on 2025-01-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_rename_account_bankaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="bank_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statements",
                to="bank.bankaccount",
                verbose_name="Conta Bancária",
            ),
        ),
    ]
