# Generated by Django 5.1.6 on 2025-03-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accountability",
            "0004_historicalrevenue_conciled_historicalrevenue_paid_and_more",
        ),
        ("bank", "0002_remove_transaction_unique__transaction_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltransaction",
            name="destination_source",
        ),
        migrations.RemoveField(
            model_name="historicaltransaction",
            name="origin_source",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="destination_source",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="origin_source",
        ),
        migrations.AddField(
            model_name="historicaltransaction",
            name="revenue",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.revenue",
                verbose_name="Receita",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="revenue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accountability.revenue",
                verbose_name="Receita",
            ),
        ),
    ]
