# Generated by Django 5.1.4 on 2025-01-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_alter_bankaccount_account_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction", name="unique__transaction_id",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("transaction_id__isnull", False)
                ),
                fields=("transaction_id",),
                name="unique__transaction_id",
            ),
        ),
    ]
