# Generated by Django 5.1.4 on 2025-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_historicaltransaction_destination_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MUNICIPAL", "Municipal"),
                    ("FEDERAL", "Federal"),
                    ("STATE", "Estadual"),
                    ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                    ("PRIVATE_SPONSOR", "Patrocinador privado"),
                ],
                default="MUNICIPAL",
                max_length=19,
                verbose_name="Origem da Fonte",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankaccount",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MUNICIPAL", "Municipal"),
                    ("FEDERAL", "Federal"),
                    ("STATE", "Estadual"),
                    ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                    ("PRIVATE_SPONSOR", "Patrocinador privado"),
                ],
                default="MUNICIPAL",
                max_length=19,
                verbose_name="Origem da Fonte",
            ),
        ),
    ]
