# Generated by Django 5.1.4 on 2025-02-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0014_expensefile_file_historicalexpensefile_file_and_more"),
        ("bank", "0003_bankaccount_origin_historicalbankaccount_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransaction",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.expense",
                verbose_name="Despesa",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accountability.expense",
                verbose_name="Despesa",
            ),
        ),
    ]
