# Generated by Django 5.1.4 on 2025-01-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_alter_bankstatement_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Tipo da Conta"
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="bank_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Id do Banco"
            ),
        ),
        migrations.AddField(
            model_name="historicalbankaccount",
            name="account_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Tipo da Conta"
            ),
        ),
        migrations.AddField(
            model_name="historicalbankaccount",
            name="bank_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Id do Banco"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="agency",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Agência"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Banco"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="agency",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Agência"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Banco"
            ),
        ),
    ]
