# Generated by Django 5.1.4 on 2025-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_historicaltransaction_expense_transaction_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "débito"),
                    ("CREDIT", "crédito"),
                    ("INT", "juros"),
                    ("DIV", "dividendos"),
                    ("FEE", "taxa"),
                    ("SRVCHG", "taxa de serviço"),
                    ("DEP", "depósito"),
                    ("ATM", "caixa eletrônico"),
                    ("POS", "ponto de venda"),
                    ("XFER", "transferência entre contas"),
                    ("CHECK", "cheque"),
                    ("PAYMENT", "fatura ou débito"),
                    ("CASH", "saque"),
                    ("DIRECTDEP", "depósito direto"),
                    ("DIRECTDEBIT", "débito automático"),
                    ("REPEATPMT", "pagamento recorrente"),
                    ("INCOME", "retorno de investimentos"),
                    ("OTHER", "outros"),
                ],
                default="OTHER",
                max_length=32,
                verbose_name="Tipo da Transação",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "débito"),
                    ("CREDIT", "crédito"),
                    ("INT", "juros"),
                    ("DIV", "dividendos"),
                    ("FEE", "taxa"),
                    ("SRVCHG", "taxa de serviço"),
                    ("DEP", "depósito"),
                    ("ATM", "caixa eletrônico"),
                    ("POS", "ponto de venda"),
                    ("XFER", "transferência entre contas"),
                    ("CHECK", "cheque"),
                    ("PAYMENT", "fatura ou débito"),
                    ("CASH", "saque"),
                    ("DIRECTDEP", "depósito direto"),
                    ("DIRECTDEBIT", "débito automático"),
                    ("REPEATPMT", "pagamento recorrente"),
                    ("INCOME", "retorno de investimentos"),
                    ("OTHER", "outros"),
                ],
                default="OTHER",
                max_length=32,
                verbose_name="Tipo da Transação",
            ),
        ),
    ]
