# Generated by Django 5.1.4 on 2025-01-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_bankaccount_account_type_bankaccount_bank_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankstatement",
            name="closing_balance",
        ),
        migrations.RemoveField(
            model_name="bankstatement",
            name="month",
        ),
        migrations.RemoveField(
            model_name="bankstatement",
            name="opening_balance",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="closing_balance",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="month",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="opening_balance",
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="closing_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Final do extrato"
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="opening_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Inicial do Extrato"
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="closing_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Final do extrato"
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="opening_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Inicial do Extrato"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Número da Conta"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Tipo da Conta"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="account",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Número da Conta"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="account_type",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Tipo da Conta"
            ),
        ),
    ]
