# Generated by Django 5.1.4 on 2025-02-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0005_alter_historicaltransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankstatement",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="bankstatement",
            name="closing_date",
        ),
        migrations.RemoveField(
            model_name="bankstatement",
            name="opening_date",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="closing_date",
        ),
        migrations.RemoveField(
            model_name="historicalbankstatement",
            name="opening_date",
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="closing_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia de Fechamento",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="opening_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia Inicial",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="reference_month",
            field=models.IntegerField(
                choices=[
                    (1, "janeiro"),
                    (2, "fevereiro"),
                    (3, "março"),
                    (4, "abril"),
                    (5, "maio"),
                    (6, "junho"),
                    (7, "julho"),
                    (8, "agosto"),
                    (9, "setembro"),
                    (10, "outubro"),
                    (11, "novembro"),
                    (12, "dezembro"),
                ],
                default=1,
                verbose_name="Mês",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="reference_year",
            field=models.IntegerField(default=0, verbose_name="Ano"),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="closing_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia de Fechamento",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="opening_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Saldo no Dia Inicial",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="reference_month",
            field=models.IntegerField(
                choices=[
                    (1, "janeiro"),
                    (2, "fevereiro"),
                    (3, "março"),
                    (4, "abril"),
                    (5, "maio"),
                    (6, "junho"),
                    (7, "julho"),
                    (8, "agosto"),
                    (9, "setembro"),
                    (10, "outubro"),
                    (11, "novembro"),
                    (12, "dezembro"),
                ],
                default=1,
                verbose_name="Mês",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="reference_year",
            field=models.IntegerField(default=0, verbose_name="Ano"),
        ),
    ]
