# Generated by Django 5.1.4 on 2025-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0006_remove_transactions_bank_statement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalbankaccount",
            name="contract",
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Transação"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Transação"
            ),
        ),
    ]
