# Generated by Django 5.1.6 on 2025-03-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_organizationtenantbaseclass"),
        ("bank", "0006_transaction_expenses_transaction_revenues"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankstatement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
    ]
