# Generated by Django 5.1.6 on 2025-03-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_delete_organizationtenantbaseclass"),
        ("bank", "0007_bankaccount_organization_bankstatement_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankstatement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
    ]
