# Generated by Django 5.1.6 on 2025-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0021_alter_favored_document_and_more"),
        ("accounts", "0019_organizationdocument"),
        (
            "bank",
            "0011_remove_bankstatement_unique_bank_statement_per_month_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("CHECKING", "Conta Corrente"), ("INVESTING", "Investimento")],
                default="CHECKING",
                help_text="Type of bank account (checking or investment)",
                max_length=9,
                verbose_name="Tipo da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("CHECKING", "Conta Corrente"), ("INVESTING", "Investimento")],
                default="CHECKING",
                help_text="Type of bank account (checking or investment)",
                max_length=9,
                verbose_name="Tipo da Conta",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("transaction_number", "memo", "bank_account"),
                name="unique_transaction_number_per_bank_account",
            ),
        ),
    ]
