# Generated by Django 5.1.4 on 2024-12-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Nome do contrato"),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor do contrato",
                    ),
                ),
                (
                    "start_of_vigency",
                    models.DateField(verbose_name="Começo da vigência"),
                ),
                ("end_of_vigency", models.DateField(verbose_name="Fim da vigência")),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
            },
        ),
        migrations.CreateModel(
            name="ContractGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Meta")),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "rascunho"),
                            ("SENT", "enviado"),
                            ("APPROVED", "aprovado"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
            },
        ),
        migrations.CreateModel(
            name="ContractItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Item")),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Descrição"),
                ),
                (
                    "total_expense",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Despesa total"
                    ),
                ),
                (
                    "is_additive",
                    models.BooleanField(default=False, verbose_name="É aditivo?"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "rascunho"),
                            ("SENT", "enviado"),
                            ("APPROVED", "aprovado"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
        migrations.CreateModel(
            name="ContractSubGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Item")),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Descrição"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_goals",
                        to="contracts.contractgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submeta",
                "verbose_name_plural": "Submetas",
            },
        ),
    ]
