# Generated by Django 5.1.4 on 2025-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractAddress",
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="complement",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="district",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="street",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Rua"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="uf",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "planejamento"),
                    ("WAITING_START", "aguardando início"),
                    ("EXECUTION", "em execução"),
                    ("FINISHED", "finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="city",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="complement",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="district",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="street",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Rua"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="uf",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "planejamento"),
                    ("WAITING_START", "aguardando início"),
                    ("EXECUTION", "em execução"),
                    ("FINISHED", "finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
    ]
