# Generated by Django 5.1.4 on 2025-01-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_remove_transaction_unique__transaction_id_and_more"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="investing_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investing_contract",
                to="bank.bankaccount",
                verbose_name="Conta Investimento",
            ),
        ),
    ]
