# Generated by Django 5.1.4 on 2025-01-27 22:47

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="contractgoal", name="status_pendencies",),
        migrations.RemoveField(model_name="contractitem", name="status_pendencies",),
        migrations.RemoveField(
            model_name="historicalcontractgoal", name="status_pendencies",
        ),
        migrations.RemoveField(
            model_name="historicalcontractitem", name="status_pendencies",
        ),
        migrations.CreateModel(
            name="ContractGoalReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "comment",
                    models.CharField(max_length=255, verbose_name="Comentário"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_reviews",
                        to="contracts.contractgoal",
                        verbose_name="Meta",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão de Meta",
                "verbose_name_plural": "Revisões de Metas",
            },
        ),
        migrations.CreateModel(
            name="ContractItemReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "comment",
                    models.CharField(max_length=255, verbose_name="Comentário"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_reviews",
                        to="contracts.contractitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão de Item",
                "verbose_name_plural": "Revisões de Itens",
            },
        ),
    ]
