# Generated by Django 5.1.4 on 2024-12-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Código do contrato"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Código do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="hired_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired_contracts",
                to="contracts.company",
                verbose_name="Contratada",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="hired_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired_manager_contracts",
                to="contracts.company",
                verbose_name="Gestor do Contratada",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="hired_company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.company",
                verbose_name="Contratada",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="hired_manager",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.company",
                verbose_name="Gestor do Contratada",
            ),
        ),
    ]
