# Generated by Django 5.1.6 on 2025-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="bidding",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Licitação"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="concession_type",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Tipo de Concessão",
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionactivity",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="contractexecutionfile",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="unit_type",
            field=models.CharField(max_length=128, verbose_name="Tipo da Unidade"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="bidding",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Licitação"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="concession_type",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Tipo de Concessão",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="unit_type",
            field=models.CharField(max_length=128, verbose_name="Tipo da Unidade"),
        ),
    ]
