# Generated by Django 5.1.4 on 2025-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractgoal",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
    ]
