# Generated by Django 6.0.5 on 2026-07-10 23:09

import uuid

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cityhall_audesp_municipality_code_and_more"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="audesp_agreement_code",
            field=models.CharField(
                blank=True,
                help_text="Código do ajuste no Sistema Audesp Fase V (campo codigo_ajuste do descritor)",
                max_length=32,
                null=True,
                verbose_name="Código do Ajuste (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="contractgoal",
            name="goal_code",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Código da Meta (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="contractgoal",
            name="periodicity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Mensal"),
                    ("BIMONTHLY", "Bimestral"),
                    ("QUARTERLY", "Trimestral"),
                    ("FOUR_MONTHLY", "Quadrimestral"),
                    ("SEMIANNUAL", "Semestral"),
                    ("PER_FISCAL_YEAR", "No Exercício"),
                    ("SINGLE", "Única"),
                ],
                max_length=15,
                null=True,
                verbose_name="Periodicidade da Meta",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="audesp_agreement_code",
            field=models.CharField(
                blank=True,
                help_text="Código do ajuste no Sistema Audesp Fase V (campo codigo_ajuste do descritor)",
                max_length=32,
                null=True,
                verbose_name="Código do Ajuste (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="goal_code",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Código da Meta (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="periodicity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Mensal"),
                    ("BIMONTHLY", "Bimestral"),
                    ("QUARTERLY", "Trimestral"),
                    ("FOUR_MONTHLY", "Quadrimestral"),
                    ("SEMIANNUAL", "Semestral"),
                    ("PER_FISCAL_YEAR", "No Exercício"),
                    ("SINGLE", "Única"),
                ],
                max_length=15,
                null=True,
                verbose_name="Periodicidade da Meta",
            ),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("MOVABLE", "Móvel"), ("IMMOVABLE", "Imóvel")],
                        max_length=9,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ACQUIRED", "Adquirido"),
                            ("CEDED", "Cedido"),
                            ("WRITTEN_OFF", "Baixado/Devolvido"),
                        ],
                        max_length=11,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        blank=True,
                        help_text="Aplicável apenas a bens móveis",
                        max_length=32,
                        null=True,
                        verbose_name="Número de Patrimônio",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="Descrição"),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Data de aquisição, cessão ou baixa/devolução, conforme o evento",
                        verbose_name="Data do Evento",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor de aquisição ou de cessão; não se aplica à baixa/devolução",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bem",
                "verbose_name_plural": "Bens",
            },
        ),
        migrations.CreateModel(
            name="ContractGoalAnnualResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="Exercício")),
                (
                    "goal_met",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Meta Atendida?"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Justificativa para Meta Não Atendida",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_results",
                        to="contracts.contractgoal",
                        verbose_name="Meta",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Anual de Meta",
                "verbose_name_plural": "Resultados Anuais de Metas",
            },
        ),
        migrations.CreateModel(
            name="ContractGoalPeriodResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        help_text="Ordinal do período dentro da periodicidade da meta (ver manual §19.1)",
                        verbose_name="Período",
                    ),
                ),
                (
                    "achieved_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Quantidade Realizada",
                    ),
                ),
                (
                    "goal_result",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Cumprida"),
                            (2, "Não Cumprida"),
                            (3, "Cumprida Parcialmente"),
                        ],
                        null=True,
                        verbose_name="Resultado da Meta Qualitativa Não Quantificável",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Justificativa da Divergência",
                    ),
                ),
                (
                    "annual_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_results",
                        to="contracts.contractgoalannualresult",
                        verbose_name="Resultado Anual",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Período de Meta",
                "verbose_name_plural": "Resultados de Períodos de Metas",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("MOVABLE", "Móvel"), ("IMMOVABLE", "Imóvel")],
                        max_length=9,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ACQUIRED", "Adquirido"),
                            ("CEDED", "Cedido"),
                            ("WRITTEN_OFF", "Baixado/Devolvido"),
                        ],
                        max_length=11,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        blank=True,
                        help_text="Aplicável apenas a bens móveis",
                        max_length=32,
                        null=True,
                        verbose_name="Número de Patrimônio",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="Descrição"),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Data de aquisição, cessão ou baixa/devolução, conforme o evento",
                        verbose_name="Data do Evento",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor de aquisição ou de cessão; não se aplica à baixa/devolução",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bem",
                "verbose_name_plural": "historical Bens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplierContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "number",
                    models.CharField(max_length=64, verbose_name="Número do Contrato"),
                ),
                (
                    "creditor_document_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "CPF"), (2, "CNPJ"), (3, "RNE")],
                        verbose_name="Tipo do Documento do Credor",
                    ),
                ),
                (
                    "creditor_document_number",
                    models.CharField(
                        max_length=32,
                        validators=[utils.validators.validate_cpf_cnpj],
                        verbose_name="Documento do Credor",
                    ),
                ),
                (
                    "creditor_name",
                    models.CharField(
                        blank=True,
                        help_text="Obrigatório quando o credor é do tipo RNE",
                        max_length=256,
                        null=True,
                        verbose_name="Nome/Razão Social do Credor",
                    ),
                ),
                ("signature_date", models.DateField(verbose_name="Data de Assinatura")),
                (
                    "validity_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pré-Estabelecida"), (2, "Indeterminada")],
                        verbose_name="Tipo de Vigência",
                    ),
                ),
                (
                    "validity_start_date",
                    models.DateField(verbose_name="Início da Vigência"),
                ),
                (
                    "validity_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Obrigatório quando validity_type é Pré-Estabelecida",
                        null=True,
                        verbose_name="Fim da Vigência",
                    ),
                ),
                ("purpose", models.CharField(max_length=1024, verbose_name="Objeto")),
                (
                    "contracting_nature",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de códigos AUDESP (1-36, ver manual §7.1)",
                        verbose_name="Natureza da Contratação",
                    ),
                ),
                (
                    "contracting_nature_other",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descrição de Outros Serviços",
                    ),
                ),
                (
                    "selection_criteria",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cotação de Preços"),
                            (2, "Dispensa"),
                            (3, "Inexigibilidade"),
                            (4, "Outros"),
                        ],
                        verbose_name="Critério de Seleção",
                    ),
                ),
                (
                    "selection_criteria_other",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descrição de Outros Critérios",
                    ),
                ),
                (
                    "purchase_regulation_article",
                    models.CharField(
                        blank=True,
                        help_text="Obrigatório para prestações de Contrato de Gestão e Termo de Parceria",
                        max_length=64,
                        null=True,
                        verbose_name="Artigo do Regulamento de Compras",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor do Contrato",
                    ),
                ),
                (
                    "value_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Global"), (2, "Mensal")],
                        verbose_name="Tipo do Valor",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contrato com Fornecedor",
                "verbose_name_plural": "historical Contratos com Fornecedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SupplierContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "number",
                    models.CharField(max_length=64, verbose_name="Número do Contrato"),
                ),
                (
                    "creditor_document_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "CPF"), (2, "CNPJ"), (3, "RNE")],
                        verbose_name="Tipo do Documento do Credor",
                    ),
                ),
                (
                    "creditor_document_number",
                    models.CharField(
                        max_length=32,
                        validators=[utils.validators.validate_cpf_cnpj],
                        verbose_name="Documento do Credor",
                    ),
                ),
                (
                    "creditor_name",
                    models.CharField(
                        blank=True,
                        help_text="Obrigatório quando o credor é do tipo RNE",
                        max_length=256,
                        null=True,
                        verbose_name="Nome/Razão Social do Credor",
                    ),
                ),
                ("signature_date", models.DateField(verbose_name="Data de Assinatura")),
                (
                    "validity_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pré-Estabelecida"), (2, "Indeterminada")],
                        verbose_name="Tipo de Vigência",
                    ),
                ),
                (
                    "validity_start_date",
                    models.DateField(verbose_name="Início da Vigência"),
                ),
                (
                    "validity_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Obrigatório quando validity_type é Pré-Estabelecida",
                        null=True,
                        verbose_name="Fim da Vigência",
                    ),
                ),
                ("purpose", models.CharField(max_length=1024, verbose_name="Objeto")),
                (
                    "contracting_nature",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de códigos AUDESP (1-36, ver manual §7.1)",
                        verbose_name="Natureza da Contratação",
                    ),
                ),
                (
                    "contracting_nature_other",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descrição de Outros Serviços",
                    ),
                ),
                (
                    "selection_criteria",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cotação de Preços"),
                            (2, "Dispensa"),
                            (3, "Inexigibilidade"),
                            (4, "Outros"),
                        ],
                        verbose_name="Critério de Seleção",
                    ),
                ),
                (
                    "selection_criteria_other",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descrição de Outros Critérios",
                    ),
                ),
                (
                    "purchase_regulation_article",
                    models.CharField(
                        blank=True,
                        help_text="Obrigatório para prestações de Contrato de Gestão e Termo de Parceria",
                        max_length=64,
                        null=True,
                        verbose_name="Artigo do Regulamento de Compras",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor do Contrato",
                    ),
                ),
                (
                    "value_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Global"), (2, "Mensal")],
                        verbose_name="Tipo do Valor",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_contracts",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato com Fornecedor",
                "verbose_name_plural": "Contratos com Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="CertificateReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GENERAL_DATA", "Dados Gerais"),
                            ("GOVERNING_BODY", "Corpo Diretivo (Prestação de Contas)"),
                            ("COUNCIL_MEMBERS", "Conselho (Prestação de Contas)"),
                            (
                                "ENTITY_RESPONSIBLE_PARTIES",
                                "Entidade Gerenciada - Responsáveis",
                            ),
                            (
                                "GRANTOR_RESPONSIBLE_PARTIES",
                                "Responsáveis do Órgão Concessor",
                            ),
                            (
                                "EVALUATION_COMMITTEE_MEMBERS",
                                "Membros da Comissão de Avaliação",
                            ),
                            ("INTERNAL_CONTROL_MEMBERS", "Membros do Controle Interno"),
                            (
                                "EXECUTION_OVERSIGHT_RESPONSIBLE_PARTIES",
                                "Responsáveis pela Fiscalização da Execução",
                            ),
                        ],
                        max_length=41,
                        verbose_name="Tipo de Certidão",
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        help_text="Identificador da certidão emitida no Sistema Audesp Fase V",
                        max_length=32,
                        verbose_name="Identificação da Certidão",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_references",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referência de Certidão",
                "verbose_name_plural": "Referências de Certidões",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("contract", "type"),
                        name="unique_certificate_reference_per_type",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contractgoalannualresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("goal", "fiscal_year"),
                name="unique_goal_annual_result_per_fiscal_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractgoalperiodresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("annual_result", "period"),
                name="unique_goal_period_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=(
                    "contract",
                    "number",
                    "signature_date",
                    "creditor_document_type",
                    "creditor_document_number",
                ),
                name="unique_supplier_contract_per_agreement",
            ),
        ),
    ]
