# Generated by Django 5.1.4 on 2025-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contracts",
            "0002_contractgoal_observations_contractitem_observations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="anual_expense",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Custo Anual",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="anual_expense",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Custo Anual",
            ),
        ),
    ]
