# Generated by Django 5.1.4 on 2025-01-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_investing_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractstep",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="contracts.contractgoal",
            ),
        ),
    ]
