# Generated by Django 5.1.4 on 2025-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_remove_contractgoal_status_pendencies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="code",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Código do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="code",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Código do contrato"
            ),
        ),
    ]
