# Generated by Django 5.1.6 on 2025-02-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_bidding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="agreement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Vigência"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="agreement_num",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número do Convênio"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="law_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data da Lei"),
        ),
        migrations.AddField(
            model_name="contract",
            name="law_num",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lei nº"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="agreement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Vigência"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="agreement_num",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número do Convênio"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="law_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data da Lei"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="law_num",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lei nº"),
        ),
    ]
