# Generated by Django 5.1.6 on 2025-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contracts",
            "0003_contract_agreement_date_contract_agreement_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="agreement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Convênio"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="law_num",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número da Lei"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="agreement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Convênio"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="law_num",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número da Lei"
            ),
        ),
    ]
