# Generated by Django 5.1.4 on 2025-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contractitem_anual_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/contract-items/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="file",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Arquivo"
            ),
        ),
    ]
