# Generated by Django 6.0.5 on 2026-08-17 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_contract_signature_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemsupplement",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Motivo da rejeição"
            ),
        ),
        migrations.AddField(
            model_name="contractitemsupplement",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Revisado em"
            ),
        ),
        migrations.AddField(
            model_name="contractitemsupplement",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_contract_item_supplements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
    ]
