# Generated by Django 5.1.4 on 2025-01-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_alter_contract_code_alter_historicalcontract_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="internal_code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Código interno para importação"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="internal_code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Código interno para importação"
            ),
        ),
    ]
