# Generated by Django 5.1.4 on 2025-01-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0004_contractaddendum_historicalcontractaddendum"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractgoal",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracts.contract",
                verbose_name="Contrato",
            ),
        ),
    ]
