# Generated by Django 5.1.4 on 2025-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contractitem_file_historicalcontractitem_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="bidding",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Licitação"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="bidding",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Licitação"
            ),
        ),
    ]
