# Generated by Django 5.1.6 on 2025-02-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contracts",
            "0004_alter_contract_agreement_date_alter_contract_law_num_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="accountability_autority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accountability_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável Contábil",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="agreement_num",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número do Convênio",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="law_num",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número da Lei",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="supervision_autority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervision_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="accountability_autority",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável Contábil",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="agreement_num",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número do Convênio",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="law_num",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número da Lei",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="supervision_autority",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável Fiscal",
            ),
        ),
    ]
