# Generated by Django 5.1.4 on 2025-02-05 18:36

import django.core.validators
import django.db.models.deletion
import django.db.models.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_bidding_historicalcontract_bidding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractExecutionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/contracts/executions",
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Atividade",
                "verbose_name_plural": "Arquivos de Atividades",
            },
        ),
        migrations.CreateModel(
            name="ContractExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                ("year", models.IntegerField(default=0, verbose_name="Ano")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="contracts.contract",
                        verbose_name="Execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Execução",
                "verbose_name_plural": "Relatórios de Execução",
                "unique_together": {("contract", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ContractExecutionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Nome")),
                (
                    "completion",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="contracts.contractexecution",
                        verbose_name="Relatório de Execução",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="contracts.contractstep",
                        verbose_name="Etapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade Executada",
                "verbose_name_plural": "Atividades Executadas",
            },
        ),
    ]
