# Generated by Django 5.1.6 on 2025-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_accountability_autority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="concession_type",
            field=models.CharField(
                choices=[
                    ("MANAGEMENT", "Contrato de Gestão"),
                    ("PARTNERSHIP", "Termo de Parceria"),
                    ("COLLABORATION", "Termo de Colaboraçã"),
                    ("DEVELOPMENTO", "Contrato de Fomento"),
                    ("AGREEMENT", "Convênio"),
                    ("GRANT", "Concessão"),
                ],
                default="MANAGEMENT",
                max_length=128,
                verbose_name="Tipo de Concessão",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="concession_type",
            field=models.CharField(
                choices=[
                    ("MANAGEMENT", "Contrato de Gestão"),
                    ("PARTNERSHIP", "Termo de Parceria"),
                    ("COLLABORATION", "Termo de Colaboraçã"),
                    ("DEVELOPMENTO", "Contrato de Fomento"),
                    ("AGREEMENT", "Convênio"),
                    ("GRANT", "Concessão"),
                ],
                default="MANAGEMENT",
                max_length=128,
                verbose_name="Tipo de Concessão",
            ),
        ),
    ]
