# Generated by Django 5.1.4 on 2025-02-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_contract_accountability_responsible_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="accountability_responsible",
            new_name="accountability_autority",
        ),
        migrations.RenameField(
            model_name="historicalcontract",
            old_name="accountability_responsible",
            new_name="accountability_autority",
        ),
        migrations.RenameField(
            model_name="historicalcontract",
            old_name="manager_responsible",
            new_name="supervision_autority",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="manager_responsible",
        ),
        migrations.AddField(
            model_name="contract",
            name="supervision_autority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervision_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
