# Generated by Django 5.1.4 on 2025-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_contractgoal_contract_contractitem_contract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="status_pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências e erros"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="status_pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências e erros"
            ),
        ),
    ]
