# Generated by Django 5.1.6 on 2025-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0006_alter_contract_concession_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractitem",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="unit_type",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Tipo da Unidade"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="unit_type",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Tipo da Unidade"
            ),
        ),
    ]
