# Generated by Django 5.1.4 on 2025-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0006_contractitem_status_pendencies_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractitem",
            options={
                "ordering": ("-total_expense",),
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
        migrations.AddField(
            model_name="contractgoal",
            name="status_pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências e erros"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="status_pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências e erros"
            ),
        ),
        migrations.AlterField(
            model_name="contractgoal",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="contractsubgoal",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="historicalcontractgoal",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="historicalcontractsubgoal",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
    ]
