# Generated by Django 5.1.4 on 2025-02-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_contractexecutionfile_contractexecution_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractexecutionactivity",
            unique_together={("execution", "step", "name")},
        ),
    ]
