# Generated by Django 5.1.4 on 2025-02-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0007_alter_contractexecutionactivity_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractexecutionactivity",
            name="description",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Descrição"
            ),
        ),
    ]
