# Generated by Django 5.1.6 on 2025-03-08 16:36

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_alter_contractitem_methodology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractInterestedPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("PROJECT_MANAGER", "Gestor de Projeto"),
                            ("FINANCIAL_MANAGER", "Gestor Financeiro"),
                            ("TECHNICAL_MANAGER", "Responsável Técnico"),
                            ("PROJECT_COORDINATOR", "Coordenador do Projeto"),
                            ("ENTITY_RESPONSIBLE", "Responsável pela Entidade"),
                            ("FISCAL_COUNCIL", "Conselho Fiscal"),
                            ("VICE_PRESIDENT", "Vice Presidente"),
                            ("TREASURER", "Tesoureiro"),
                            ("SECRETARY", "Secretário"),
                        ],
                        default="PROJECT_MANAGER",
                        max_length=19,
                        verbose_name="Interesse",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_parts",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_parts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={"verbose_name": "Partes Interessadas",},
        ),
    ]
