# Generated by Django 5.1.4 on 2025-01-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_remove_bankaccount_contract_and_more"),
        ("contracts", "0007_alter_contractitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="checking_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checking_account",
                to="bank.bankaccount",
                verbose_name="Conta Corrente",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="investing_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investing_contracts",
                to="bank.bankaccount",
                verbose_name="Conta Investimento",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="checking_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bank.bankaccount",
                verbose_name="Conta Corrente",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="investing_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bank.bankaccount",
                verbose_name="Conta Investimento",
            ),
        ),
    ]
