# Generated by Django 5.1.6 on 2025-03-08 18:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0008_contractinterestedpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Telefone da empresa",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Telefone da empresa",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
