# Generated by Django 5.1.4 on 2025-01-19 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "contracts",
            "0008_contract_checking_account_contract_investing_account_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContractSubGoal",
            new_name="ContractStep",
        ),
        migrations.RenameModel(
            old_name="HistoricalContractSubGoal",
            new_name="HistoricalContractStep",
        ),
        migrations.AlterModelOptions(
            name="contractstep",
            options={"verbose_name": "Etapa", "verbose_name_plural": "Etapas"},
        ),
        migrations.AlterModelOptions(
            name="historicalcontractstep",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Etapa",
                "verbose_name_plural": "historical Etapas",
            },
        ),
    ]
