# Generated by Django 5.1.4 on 2025-02-05 20:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_contractexecutionactivity_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractexecutionactivity", name="completion",
        ),
        migrations.AddField(
            model_name="contractexecutionactivity",
            name="percentage",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentagem Completa",
            ),
        ),
    ]
