# Generated by Django 5.1.4 on 2025-02-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0009_remove_contractexecutionactivity_completion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractexecutionfile",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="contracts.contractexecution",
                verbose_name="Relatório de Execução",
            ),
        ),
        migrations.AddField(
            model_name="contractexecutionfile",
            name="name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Nome"
            ),
        ),
    ]
