# Generated by Django 5.1.6 on 2025-03-08 18:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_company_phone_number_historicalcompany_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Telefone da empresa",
                max_length=128,
                null=True,
                region="BR",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Telefone da empresa",
                max_length=128,
                null=True,
                region="BR",
            ),
        ),
    ]
