# Generated by Django 5.1.4 on 2025-02-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0011_contractexecution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data Final"),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data Inicial"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data Final"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data Inicial"),
        ),
    ]
