# Generated by Django 5.1.6 on 2025-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_merge_20250308_1844"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="counterpart_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor repassado por contrapartida de parceiro",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="municipal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor repassado pelo município",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="counterpart_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor repassado por contrapartida de parceiro",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="municipal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor repassado pelo município",
            ),
        ),
    ]
