# Generated by Django 5.1.4 on 2025-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_alter_contractitem_nature_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractgoal", name="description",),
        migrations.RemoveField(
            model_name="historicalcontractgoal", name="description",
        ),
        migrations.AddField(
            model_name="contractgoal",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AddField(
            model_name="contractgoal",
            name="objective",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Objetivo"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractgoal",
            name="objective",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Objetivo"
            ),
        ),
        migrations.AlterField(
            model_name="contractgoal",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Item"),
        ),
        migrations.AlterField(
            model_name="historicalcontractgoal",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Item"),
        ),
    ]
