# Generated by Django 5.1.4 on 2025-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_remove_contractgoal_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contractstep", name="description",),
        migrations.RemoveField(
            model_name="historicalcontractstep", name="description",
        ),
        migrations.AddField(
            model_name="contractstep",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AddField(
            model_name="contractstep",
            name="objective",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Objetivo"
            ),
        ),
        migrations.AddField(
            model_name="contractstep",
            name="resources",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Recursos"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractstep",
            name="methodology",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Metodologia"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractstep",
            name="objective",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Objetivo"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractstep",
            name="resources",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Recursos"
            ),
        ),
    ]
