# Generated by Django 5.1.4 on 2025-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0012_contractitem_end_date_contractitem_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="concession_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Tipo de Concessão"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="concession_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Tipo de Concessão"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="month_expense",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Custo Mensal Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="month_expense",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Custo Mensal Unitário"
            ),
        ),
    ]
