# Generated by Django 5.1.4 on 2025-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0013_contract_concession_type_contractitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "planejamento"),
                    ("EXECUTION", "em execução"),
                    ("FINISHED", "finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "planejamento"),
                    ("EXECUTION", "em execução"),
                    ("FINISHED", "finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
    ]
