# Generated by Django 5.1.6 on 2025-03-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_alter_contract_counterpart_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="source",
            field=models.CharField(
                choices=[
                    ("CITY_HALL", "Prefeitura"),
                    ("COUNTERPART", "Contrapartida de Parceiro"),
                ],
                default="CITY_HALL",
                max_length=11,
                verbose_name="Fonte do Recurso",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="source",
            field=models.CharField(
                choices=[
                    ("CITY_HALL", "Prefeitura"),
                    ("COUNTERPART", "Contrapartida de Parceiro"),
                ],
                default="CITY_HALL",
                max_length=11,
                verbose_name="Fonte do Recurso",
            ),
        ),
    ]
