# Generated by Django 5.1.4 on 2025-02-09 22:51

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0014_alter_contract_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractItemNewValueRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_REVIEW", "Em revisão"),
                            ("REJECTED", "Rejeitado"),
                            ("APPROVED", "Aprovado"),
                        ],
                        default="IN_REVIEW",
                        max_length=9,
                        verbose_name="Status",
                    ),
                ),
                (
                    "month_raise",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Incrementeo Mensal",
                    ),
                ),
                (
                    "anual_raise",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Incremento Anual"
                    ),
                ),
                (
                    "downgrade_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downgrade_requests",
                        to="contracts.contractitem",
                        verbose_name="Item para diminuir valor",
                    ),
                ),
                (
                    "raise_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raise_requests",
                        to="contracts.contractitem",
                        verbose_name="Item para aumentar valor",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_value_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Valor Item",
                "verbose_name_plural": "Solicitações de Valores Item",
            },
        ),
    ]
