# Generated by Django 5.1.6 on 2025-03-09 18:19

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0014_contractitem_source_historicalcontractitem_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractMonthTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CITY_HALL", "Prefeitura"),
                            ("COUNTERPART", "Contrapartida"),
                        ],
                        default="CITY_HALL",
                        verbose_name="Fonte do Repasse",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor do Repasse"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_transfers",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repasse Mensal",
                "verbose_name_plural": "Repasses Mensais",
            },
        ),
    ]
