# Generated by Django 5.1.6 on 2025-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_contractmonthtransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmonthtransfer",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "janeiro"),
                    (2, "fevereiro"),
                    (3, "março"),
                    (4, "abril"),
                    (5, "maio"),
                    (6, "junho"),
                    (7, "julho"),
                    (8, "agosto"),
                    (9, "setembro"),
                    (10, "outubro"),
                    (11, "novembro"),
                    (12, "dezembro"),
                ],
                default=1,
                verbose_name="Mês",
            ),
        ),
        migrations.AddField(
            model_name="contractmonthtransfer",
            name="year",
            field=models.IntegerField(default=0, verbose_name="Ano"),
        ),
    ]
