# Generated by Django 5.1.4 on 2025-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_contractitemnewvaluerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemnewvaluerequest",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Motivo da rejeição"
            ),
        ),
    ]
