# Generated by Django 5.1.6 on 2025-03-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_delete_organizationtenantbaseclass"),
        ("contracts", "0018_contractaddendum_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractaddendum",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractexecution",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionactivity",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionfile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractgoal",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractgoalreview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractinterestedpart",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractitemnewvaluerequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractitemreview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractmonthtransfer",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contractstep",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractaddendum",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractgoal",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractstep",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
    ]
