# Generated by Django 5.1.6 on 2025-03-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_committee"),
        ("contracts", "0019_alter_company_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="accounts.committee",
                verbose_name="Comitê",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.committee",
                verbose_name="Comitê",
            ),
        ),
    ]
