# Generated by Django 5.1.6 on 2025-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_cityhall_unique_together_and_more"),
        ("contracts", "0020_contract_committee_historicalcontract_committee"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractexecutionactivity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contractexecutionactivity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("execution", "step", "name"),
                name="unique_activity_per_execution_step",
            ),
        ),
    ]
