# Generated by Django 5.1.6 on 2025-03-24 21:32

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_user_options"),
        ("contracts", "0021_alter_contractexecutionactivity_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="bidding",
            field=models.CharField(max_length=128, verbose_name="Licitação"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="internal_code",
            field=models.PositiveIntegerField(
                verbose_name="Código interno para importação"
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionactivity",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="contractexecutionfile",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="contracts.contractexecution",
                verbose_name="Relatório de Execução",
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionfile",
            name="file",
            field=models.FileField(
                upload_to="uploads/contracts/executions", verbose_name="Arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="contractexecutionfile",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="bidding",
            field=models.CharField(max_length=128, verbose_name="Licitação"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="internal_code",
            field=models.PositiveIntegerField(
                verbose_name="Código interno para importação"
            ),
        ),
        migrations.CreateModel(
            name="ContractItemPurchaseProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_processes",
                        to="contracts.contractitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo de Compra",
                "verbose_name_plural": "Processos de Compra",
            },
        ),
    ]
