# Generated by Django 5.1.6 on 2025-03-24 21:39

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_options'),
        ('contracts', '0022_alter_contract_bidding_alter_contract_internal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractItemPurchaseProcessDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/contract-item-purchase-process-documents/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Documento do Processo de Compra',
                'verbose_name_plural': 'Documentos do Processo de Compra',
            },
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='aquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Aquisição'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='aquisition_parcel_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='aquisition_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Aquisição'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='observations',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='parcel_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento das Parcelas'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='supplier',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço do Fornecedor'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='supplier_document',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Documento do Fornecedor'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email do Fornecedor'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocess',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefone do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='contractitempurchaseprocess',
            name='status',
            field=models.CharField(choices=[('ANALYZING', 'Analisando Opções'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado')], default='ANALYZING', max_length=22, verbose_name='Status de Compra'),
        ),
        migrations.AddIndex(
            model_name='contractitempurchaseprocess',
            index=models.Index(fields=['item'], name='contracts_c_item_id_85ce3c_idx'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocessdocument',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='contractitempurchaseprocessdocument',
            name='purchase_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contractitempurchaseprocess', verbose_name='Processo de Compra'),
        ),
    ]
