# Generated by Django 5.1.6 on 2025-03-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0023_contractitempurchaseprocessdocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractitempurchaseprocessdocument",
            name="purchase_process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="contracts.contractitem",
                verbose_name="Processo de Compra",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="aquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Aquisição"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="aquisition_parcel_quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade de Parcelas"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="aquisition_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor da Aquisição",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="parcel_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Vencimento das Parcelas"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("ANALYZING", "Analisando Opções"),
                    ("IN_PROGRESS", "Em Andamento"),
                    ("FINISHED", "Finalizado"),
                ],
                default="ANALYZING",
                max_length=22,
                verbose_name="Status de Compra",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Fornecedor"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="supplier_address",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Endereço do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="supplier_document",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Documento do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="supplier_email",
            field=models.EmailField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Email do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="supplier_phone",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Telefone do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="aquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Aquisição"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="aquisition_parcel_quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade de Parcelas"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="aquisition_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor da Aquisição",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="parcel_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Vencimento das Parcelas"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("ANALYZING", "Analisando Opções"),
                    ("IN_PROGRESS", "Em Andamento"),
                    ("FINISHED", "Finalizado"),
                ],
                default="ANALYZING",
                max_length=22,
                verbose_name="Status de Compra",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Fornecedor"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="supplier_address",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Endereço do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="supplier_document",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Documento do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="supplier_email",
            field=models.EmailField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Email do Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="supplier_phone",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Telefone do Fornecedor",
            ),
        ),
        migrations.DeleteModel(
            name="ContractItemPurchaseProcess",
        ),
    ]
