# Generated by Django 5.1.6 on 2025-03-24 22:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contracts",
            "0024_alter_contractitempurchaseprocessdocument_purchase_process_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractitem",
            name="aquisition_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Valor da Aquisição",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="aquisition_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Valor da Aquisição",
            ),
        ),
    ]
