# Generated by Django 5.1.6 on 2025-03-25 12:41

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_user_options"),
        ("contracts", "0025_alter_contractitem_aquisition_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractItemSupplement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_REVIEW", "Em revisão"),
                            ("REJECTED", "Rejeitado"),
                            ("APPROVED", "Aprovado"),
                        ],
                        default="IN_REVIEW",
                        max_length=9,
                        verbose_name="Status",
                    ),
                ),
                (
                    "suplement_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor do suplemento",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplements",
                        to="contracts.contractitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suplemento de Item",
                "verbose_name_plural": "Suplementos de Itens",
                "ordering": ("-suplement_value",),
            },
        ),
    ]
