# Generated by Django 5.1.6 on 2025-03-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0026_contractitemsupplement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractinterestedpart",
            options={
                "verbose_name": "Parte Interessada",
                "verbose_name_plural": "Partes Interessadas",
            },
        ),
        migrations.RemoveField(
            model_name="contractitempurchaseprocessdocument",
            name="purchase_process",
        ),
        migrations.AddField(
            model_name="contractitempurchaseprocessdocument",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_documents",
                to="contracts.contractitem",
                verbose_name="Processo de Compra",
            ),
        ),
    ]
