# Generated by Django 5.1.6 on 2025-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0027_alter_contractinterestedpart_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitempurchaseprocessdocument",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Nome"
            ),
        ),
    ]
