# Generated by Django 5.1.6 on 2025-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_organizationdocument"),
        ("contracts", "0028_contractitempurchaseprocessdocument_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractexecution",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contractexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("contract", "month", "year"),
                name="unique_execution_per_contract_month_year",
            ),
        ),
    ]
