# Generated by Django 5.1.6 on 2025-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0030_contract_original_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="original_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor original do contrato",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="original_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor original do contrato",
            ),
        ),
    ]
