# Generated by Django 5.1.6 on 2025-08-19 17:08

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organizationdocument'),
        ('contracts', '0031_alter_contract_original_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaddendum',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/contract-addendums/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='historicalcontractaddendum',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('type', models.CharField(choices=[('ADDENDUM', 'Aditivo'), ('CONTRACT', 'Contrato'), ('OTHER', 'Outro')], default='OTHER', max_length=128, verbose_name='Tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/contract-documents/', verbose_name='Arquivo')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Contrato')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contrato',
            },
        ),
    ]
