# Generated by Django 5.1.6 on 2025-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0033_alter_contract_bidding_alter_contract_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractmonthtransfer",
            name="source",
            field=models.CharField(
                choices=[("CITY_HALL", "Prefeitura"), ("COUNTERPART", "Contrapartida")],
                default="CITY_HALL",
                max_length=255,
                verbose_name="Fonte do Repasse",
            ),
        ),
    ]
