# Generated by Django 5.1.6 on 2025-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_alter_contractgoalreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstep',
            name='resources',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Recursos'),
        ),
        migrations.AlterField(
            model_name='historicalcontractstep',
            name='resources',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Recursos'),
        ),
    ]
