# Generated by Django 5.1.6 on 2025-10-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0038_alter_contractgoal_methodology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planejamento"),
                    ("EXECUTION", "Em Execução"),
                    ("FINISHED", "Finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planejamento"),
                    ("EXECUTION", "Em Execução"),
                    ("FINISHED", "Finalizado"),
                ],
                default="PLANNING",
                max_length=13,
                verbose_name="Status",
            ),
        ),
    ]
