# Generated by Django 5.2 on 2025-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_alter_contractgoal_methodology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='official_journal_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link Oficial do Governo'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='official_journal_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link Oficial do Governo'),
        ),
    ]
