# Generated by Django 5.2 on 2025-10-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_contract_official_journal_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='official_journal_link',
            new_name='official_government_link',
        ),
        migrations.RenameField(
            model_name='historicalcontract',
            old_name='official_journal_link',
            new_name='official_government_link',
        ),
    ]
