# Generated by Django 5.1.6 on 2025-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_alter_contract_status_and_more'),
        ('contracts', '0040_rename_official_journal_link_contract_official_government_link_and_more'),
    ]

    operations = [
    ]
