# Generated by Django 6.0.5 on 2026-05-14 00:14

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone
import phonenumber_field.modelfields
import simple_history.models
import utils.fields
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Nome de usuário opcional. Se não fornecido, o email será usado.', max_length=150, null=True)),
                ('email', utils.fields.LowerCaseEmailField(help_text='Endereço de email do usuário. Será usado para login e notificações.', max_length=254, unique=True)),
                ('cpf', models.CharField(blank=True, help_text='Número do CPF do usuário. Deve ser único dentro da organização.', max_length=16, null=True, validators=[utils.validators.validate_cpf], verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, help_text='Número do CNPJ do usuário. Deve ser único dentro da organização.', max_length=18, null=True, validators=[utils.validators.validate_cnpj], verbose_name='CNPJ')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone pessoal no formato brasileiro (ex: +55 11 99999-9999)', max_length=128, null=True, region='BR')),
                ('password_expires_at', models.DateTimeField(blank=True, help_text='Data em que a senha do usuário expira', null=True, verbose_name='Data de Expiração da Senha')),
                ('password_redefined', models.BooleanField(default=False, help_text='Indica se o usuário já alterou sua senha inicial', verbose_name='Senha Redefinida')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Data em que o usuário foi desativado', null=True, verbose_name='Data de Desativação')),
                ('access_level', models.CharField(choices=[('MASTER', 'Master'), ('CIVIL_SERVANT', 'Funcionário público'), ('FOLDER_MANAGER', 'Gestor da pasta'), ('ORGANIZATION_ACCOUNTANT', 'Contador / funcionário da organização'), ('COMMITTEE_MEMBER', 'Membro do comitê')], default='ORGANIZATION_ACCOUNTANT', help_text='Nível de acesso do usuário no sistema. Define suas permissões.', max_length=23, verbose_name='Nível de Acesso')),
                ('position', models.CharField(blank=True, help_text='Cargo ou função do usuário na organização', max_length=150, null=True, verbose_name='cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('areas', models.ManyToManyField(help_text='Áreas dentro da organização que este usuário tem acesso', related_name='users', to='accounts.area')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CityHall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Prefeitura')),
                ('mayor', models.CharField(max_length=256, verbose_name='Prefeito')),
                ('document', models.CharField(help_text='CPF ou CNPJ da prefeitura', max_length=32, validators=[utils.validators.validate_cpf_cnpj], verbose_name='Documento')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Prefeitura',
                'verbose_name_plural': 'Prefeituras',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('document',), name='unique_cityhall_document')],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounts.cityhall', verbose_name='Prefeitura'),
        ),
        migrations.CreateModel(
            name='HistoricalCityHall',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Prefeitura')),
                ('mayor', models.CharField(max_length=256, verbose_name='Prefeito')),
                ('document', models.CharField(help_text='CPF ou CNPJ da prefeitura', max_length=32, validators=[utils.validators.validate_cpf_cnpj], verbose_name='Documento')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='cargo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Prefeitura',
                'verbose_name_plural': 'historical Prefeituras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('owner', models.CharField(blank=True, max_length=256, null=True, verbose_name='Presidente')),
                ('document', models.CharField(blank=True, help_text='CPF ou CNPJ da organização', max_length=32, null=True, validators=[utils.validators.validate_cpf_cnpj], verbose_name='Documento')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='cargo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city_hall', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.cityhall', verbose_name='Prefeitura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Organização',
                'verbose_name_plural': 'historical Organizações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('owner', models.CharField(blank=True, max_length=256, null=True, verbose_name='Presidente')),
                ('document', models.CharField(blank=True, help_text='CPF ou CNPJ da organização', max_length=32, null=True, validators=[utils.validators.validate_cpf_cnpj], verbose_name='Documento')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='cargo')),
                ('city_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='accounts.cityhall', verbose_name='Prefeitura')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='HistoricalArea',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city_hall', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.cityhall', verbose_name='Prefeitura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Area',
                'verbose_name_plural': 'historical Areas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome do Comitê')),
                ('city_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='accounts.cityhall', verbose_name='Prefeitura')),
                ('members', models.ManyToManyField(blank=True, related_name='committees', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Comitê',
                'verbose_name_plural': 'Comitês',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounts.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(help_text='A organização à qual este usuário pertence', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization', verbose_name='organization'),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('balance', 'Balanço Patrimonial'), ('dre', 'Demonstrativo do Resultado do Exercício'), ('statute', 'Estatuto Social'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to='organization_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Arquivo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Visível no portal da transparência')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Organização',
                'verbose_name_plural': 'Documentos da Organização',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('city_hall', 'document'), name='unique_organization_document_per_cityhall'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cpf'], name='accounts_us_cpf_c8d8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cnpj'], name='accounts_us_cnpj_11f172_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['access_level'], name='accounts_us_access__504911_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'access_level'], name='accounts_us_organiz_ccd728_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_expires_at'], name='accounts_us_passwor_978854_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('organization', 'cpf', 'cnpj'), ('organization', 'email')},
        ),
    ]
