# Generated by Django 6.0.5 on 2026-07-10 23:09

import uuid

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityhall",
            name="audesp_municipality_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Código do município no Sistema Audesp, conforme planilha em tce.sp.gov.br/audesp/coletor",
                null=True,
                verbose_name="Código do Município (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcityhall",
            name="audesp_municipality_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Código do município no Sistema Audesp, conforme planilha em tce.sp.gov.br/audesp/coletor",
                null=True,
                verbose_name="Código do Município (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="audesp_entity_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Código da entidade no Sistema Audesp — identifica o órgão responsável pela prestação de contas ao TCESP",
                null=True,
                verbose_name="Código da Entidade (AUDESP)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="audesp_entity_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Código da entidade no Sistema Audesp — identifica o órgão responsável pela prestação de contas ao TCESP",
                null=True,
                verbose_name="Código da Entidade (AUDESP)",
            ),
        ),
        migrations.CreateModel(
            name="CededServant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "cession_start_date",
                    models.DateField(verbose_name="Data Inicial da Cessão"),
                ),
                (
                    "cession_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final da Cessão"
                    ),
                ),
                (
                    "public_position_held",
                    models.CharField(
                        max_length=128, verbose_name="Cargo Público Ocupado"
                    ),
                ),
                (
                    "role_performed",
                    models.CharField(
                        max_length=128,
                        verbose_name="Função Desempenhada na Entidade Beneficiária",
                    ),
                ),
                (
                    "payment_burden",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Órgão Concessor"),
                            (2, "Entidade Beneficiada"),
                            (3, "Ambos"),
                        ],
                        verbose_name="Ônus do Pagamento",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servidor Cedido",
                "verbose_name_plural": "Servidores Cedidos",
            },
        ),
        migrations.CreateModel(
            name="CededServantRemunerationPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("year", models.IntegerField(verbose_name="Ano")),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Carga Horária"
                    ),
                ),
                (
                    "gross_remuneration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Remuneração Bruta",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
                (
                    "servant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remuneration_periods",
                        to="accounts.cededservant",
                        verbose_name="Servidor Cedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remuneração Mensal de Servidor Cedido",
                "verbose_name_plural": "Remunerações Mensais de Servidores Cedidos",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="Data de Admissão")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "cbo",
                    models.CharField(
                        help_text="Código Brasileiro de Ocupação. Para estagiários, usar o código equivalente à função exercida.",
                        max_length=16,
                        verbose_name="CBO",
                    ),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        help_text="Cartão Nacional de Saúde — obrigatório quando o CBO corresponde a médico (subgrupo 225)",
                        max_length=15,
                        null=True,
                        verbose_name="CNS",
                    ),
                ),
                (
                    "contractual_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Situação no início do exercício",
                        max_digits=12,
                        verbose_name="Salário Contratual",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empregado",
                "verbose_name_plural": "Empregados",
            },
        ),
        migrations.CreateModel(
            name="EmployeeRemunerationPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("year", models.IntegerField(verbose_name="Ano")),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Carga Horária"
                    ),
                ),
                (
                    "gross_remuneration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Remuneração Bruta",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remuneration_periods",
                        to="accounts.employee",
                        verbose_name="Empregado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remuneração Mensal de Empregado",
                "verbose_name_plural": "Remunerações Mensais de Empregados",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCededServant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "cession_start_date",
                    models.DateField(verbose_name="Data Inicial da Cessão"),
                ),
                (
                    "cession_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final da Cessão"
                    ),
                ),
                (
                    "public_position_held",
                    models.CharField(
                        max_length=128, verbose_name="Cargo Público Ocupado"
                    ),
                ),
                (
                    "role_performed",
                    models.CharField(
                        max_length=128,
                        verbose_name="Função Desempenhada na Entidade Beneficiária",
                    ),
                ),
                (
                    "payment_burden",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Órgão Concessor"),
                            (2, "Entidade Beneficiada"),
                            (3, "Ambos"),
                        ],
                        verbose_name="Ônus do Pagamento",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Servidor Cedido",
                "verbose_name_plural": "historical Servidores Cedidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="Data de Admissão")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "cbo",
                    models.CharField(
                        help_text="Código Brasileiro de Ocupação. Para estagiários, usar o código equivalente à função exercida.",
                        max_length=16,
                        verbose_name="CBO",
                    ),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        help_text="Cartão Nacional de Saúde — obrigatório quando o CBO corresponde a médico (subgrupo 225)",
                        max_length=15,
                        null=True,
                        verbose_name="CNS",
                    ),
                ),
                (
                    "contractual_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Situação no início do exercício",
                        max_digits=12,
                        verbose_name="Salário Contratual",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Empregado",
                "verbose_name_plural": "historical Empregados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="cededservant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "cpf", "cession_start_date"),
                name="unique_ceded_servant_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="cededservantremunerationperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("servant", "year", "month"),
                name="unique_ceded_servant_remuneration_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "cpf", "admission_date"),
                name="unique_employee_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeremunerationperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("employee", "year", "month"),
                name="unique_employee_remuneration_period",
            ),
        ),
    ]
