# Generated by Django 5.1.4 on 2025-01-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="city_hall",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.cityhall",
                verbose_name="Prefeitura",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="city_hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="accounts.cityhall",
                verbose_name="Prefeitura",
            ),
        ),
    ]
