# Generated by Django 5.1.4 on 2024-12-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cityhall_historicalcityhall"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("MASTER", "master"),
                    ("CIVIL_SERVANT", "Funcionário público"),
                    ("FOLDER_MANAGER", "Gestor da pasta"),
                    ("ONG_ACCOUNTANT", "Contador / funcionário da ong"),
                ],
                default="ONG_ACCOUNTANT",
                max_length=14,
                verbose_name="Nível de Acesso",
            ),
        ),
    ]
