# Generated by Django 5.1.4 on 2025-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityhall",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="cargo"
            ),
        ),
        migrations.AddField(
            model_name="historicalcityhall",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="cargo"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="cargo"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="cargo"
            ),
        ),
    ]
