# Generated by Django 5.1.4 on 2025-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_historicalorganization_city_hall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityhall",
            name="document",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="cityhall",
            name="mayor",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Prefeito"
            ),
        ),
        migrations.AddField(
            model_name="historicalcityhall",
            name="document",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="historicalcityhall",
            name="mayor",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Prefeito"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="document",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="owner",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Presidente"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="document",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Presidente"
            ),
        ),
    ]
