# Generated by Django 5.1.6 on 2025-03-08 18:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Telefone pessoal do usuário",
                max_length=128,
                null=True,
                region="BR",
            ),
        ),
    ]
