# Generated by Django 5.1.4 on 2025-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_cityhall_document_cityhall_mayor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Cpf"
            ),
        ),
    ]
