# Generated by Django 5.1.4 on 2024-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_area_historicalarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="historicalarea",
            name="description",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Descrição"
            ),
        ),
    ]
