# Generated by Django 5.1.4 on 2024-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_area_description_historicalarea_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="area", name="users",),
        migrations.AddField(
            model_name="user",
            name="areas",
            field=models.ManyToManyField(related_name="users", to="accounts.area"),
        ),
    ]
