# Generated by Django 5.1.4 on 2024-12-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_area_users_user_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="city_hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="accounts.cityhall",
                verbose_name="Prefeitura",
            ),
        ),
        migrations.AddField(
            model_name="historicalarea",
            name="city_hall",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.cityhall",
                verbose_name="Prefeitura",
            ),
        ),
    ]
