# Generated by Django 5.1.6 on 2025-03-22 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_organizationtenantbaseclass"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationTenantBaseClass",
        ),
    ]
