# Generated by Django 5.1.6 on 2025-03-22 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="committees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membros",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("MASTER", "master"),
                    ("CIVIL_SERVANT", "Funcionário público"),
                    ("FOLDER_MANAGER", "Gestor da pasta"),
                    (
                        "ORGANIZATION_ACCOUNTANT",
                        "Contador / funcionário da organização",
                    ),
                    ("COMMITTEE_MEMBER", "Membro do comitê"),
                ],
                default="ORGANIZATION_ACCOUNTANT",
                max_length=23,
                verbose_name="Nível de Acesso",
            ),
        ),
    ]
