# Generated by Django 5.1.6 on 2025-03-22 23:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models

import utils.fields
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_committee_members_alter_user_access_level"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AlterField(
            model_name="cityhall",
            name="document",
            field=models.CharField(
                help_text="CPF ou CNPJ da prefeitura",
                max_length=32,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcityhall",
            name="document",
            field=models.CharField(
                help_text="CPF ou CNPJ da prefeitura",
                max_length=32,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CPF ou CNPJ da organização",
                max_length=32,
                null=True,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CPF ou CNPJ da organização",
                max_length=32,
                null=True,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("MASTER", "master"),
                    ("CIVIL_SERVANT", "Funcionário público"),
                    ("FOLDER_MANAGER", "Gestor da pasta"),
                    (
                        "ORGANIZATION_ACCOUNTANT",
                        "Contador / funcionário da organização",
                    ),
                    ("COMMITTEE_MEMBER", "Membro do comitê"),
                ],
                default="ORGANIZATION_ACCOUNTANT",
                help_text="Nível de acesso do usuário no sistema. Define suas permissões.",
                max_length=23,
                verbose_name="Nível de Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="areas",
            field=models.ManyToManyField(
                help_text="Áreas dentro da organização que este usuário tem acesso",
                related_name="users",
                to="accounts.area",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                help_text="Número do CPF do usuário. Deve ser único dentro da organização.",
                max_length=16,
                validators=[utils.validators.validate_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=utils.fields.LowerCaseEmailField(
                help_text="Endereço de email do usuário. Será usado para login e notificações.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                help_text="A organização à qual este usuário pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Data em que a senha do usuário irá expirar. Se None, a senha nunca expira.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_redefined",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário já alterou sua senha inicial",
                verbose_name="Senha Redefinida",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Número de telefone pessoal no formato brasileiro (ex: +55 11 99999-9999)",
                max_length=128,
                null=True,
                region="BR",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Cargo ou função do usuário na organização",
                max_length=150,
                null=True,
                verbose_name="cargo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Nome de usuário opcional. Se não fornecido, o email será usado.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cityhall",
            unique_together={("document",)},
        ),
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together={("city_hall", "document")},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={
                ("organization", "cpf"),
                ("organization", "email"),
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["cpf"], name="accounts_us_cpf_c8d8a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["access_level"], name="accounts_us_access__504911_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "access_level"],
                name="accounts_us_organiz_ccd728_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["password_expires_at"],
                name="accounts_us_passwor_978854_idx",
            ),
        ),
    ]
