# Generated by Django 5.1.6 on 2025-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_user_options_alter_cityhall_document_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cityhall",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que a senha do usuário expira",
                null=True,
                verbose_name="Data de Expiração da Senha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cityhall",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("document",),
                name="unique_cityhall_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("city_hall", "document"),
                name="unique_organization_document_per_cityhall",
            ),
        ),
    ]
