# Generated by Django 5.1.6 on 2025-04-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o usuário foi desativado",
                null=True,
                verbose_name="Data de Desativação",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("MASTER", "Master"),
                    ("CIVIL_SERVANT", "Funcionário público"),
                    ("FOLDER_MANAGER", "Gestor da pasta"),
                    (
                        "ORGANIZATION_ACCOUNTANT",
                        "Contador / funcionário da organização",
                    ),
                    ("COMMITTEE_MEMBER", "Membro do comitê"),
                ],
                default="ORGANIZATION_ACCOUNTANT",
                help_text="Nível de acesso do usuário no sistema. Define suas permissões.",
                max_length=23,
                verbose_name="Nível de Acesso",
            ),
        ),
    ]
