# Generated by Django 5.1.6 on 2025-04-03 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_user_deactivated_at_alter_user_access_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
    ]
