# Generated by Django 5.1.6 on 2025-04-03 18:03

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_user_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("organization", "cpf"), ("organization", "email")},
        ),
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Número do CNPJ do usuário. Deve ser único dentro da organização.",
                max_length=18,
                null=True,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Número do CPF do usuário. Deve ser único dentro da organização.",
                max_length=16,
                null=True,
                validators=[utils.validators.validate_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={
                ("organization", "cnpj"),
                ("organization", "cpf"),
                ("organization", "email"),
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["cnpj"], name="accounts_us_cnpj_11f172_idx"),
        ),
    ]
