# Generated by Django 5.1.6 on 2025-04-03 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0016_alter_user_unique_together_user_cnpj_alter_user_cpf_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={
                ("organization", "cpf", "cnpj"),
                ("organization", "email"),
            },
        ),
    ]
