# Generated by Django 5.1.6 on 2025-04-03 22:03

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_user_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Número do CNPJ do usuário. Deve ser único dentro da organização.",
                max_length=18,
                null=True,
                validators=[utils.validators.validate_cnpj],
                verbose_name="CNPJ",
            ),
        ),
    ]
