# Generated by Django 5.1.6 on 2025-04-04 01:26

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_user_cnpj"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("balance", "Balanço Patrimonial"),
                            ("dre", "Demonstrativo do Resultado do Exercício"),
                            ("statute", "Estatuto Social"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "file",
                    models.FileField(
                        upload_to="organization_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "xls", "xlsx"]
                            )
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Visível no portal da transparência"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Organização",
                "verbose_name_plural": "Documentos da Organização",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
