# Generated by Django 6.0.5 on 2026-07-10 23:09

import uuid

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0003_expense_apportionment_percentage_and_more"),
        ("transparency_portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTransparencyChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "has_website",
                    models.BooleanField(
                        default=False,
                        help_text="Lei Federal nº 12.527/11 (LAI), art. 8º §2º",
                        verbose_name="Mantém Sítio na Internet?",
                    ),
                ),
                (
                    "websites",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Sítios na Internet"
                    ),
                ),
                (
                    "art7_8_1_organizational_structure",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Competência e Estrutura Organizacional",
                    ),
                ),
                (
                    "art7_8_1_contact_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Endereço, e-mail, telefones e horários de atendimento",
                    ),
                ),
                (
                    "art7_8_1_transfer_records",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Registro de repasses ou transferências de recursos financeiros",
                    ),
                ),
                (
                    "art7_8_1_expense_records",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Registros de despesas realizadas com recursos públicos",
                    ),
                ),
                (
                    "art7_8_1_procurement_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Informações sobre contratações de bens e serviços",
                    ),
                ),
                (
                    "art7_8_1_goals_tracking_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Informações para acompanhamento de programas/ações/metas",
                    ),
                ),
                (
                    "art7_8_1_faq",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Respostas a perguntas mais frequentes da sociedade",
                    ),
                ),
                (
                    "art7_8_1_audit_results",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Resultado de inspeções, auditorias e prestações de contas",
                    ),
                ),
                (
                    "art8_3_content_search_tool",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Ferramenta de pesquisa de conteúdo",
                    ),
                ),
                (
                    "art8_3_open_format_reports",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Geração de relatórios em formatos eletrônicos abertos",
                    ),
                ),
                (
                    "art8_3_automated_external_access",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Acesso automatizado por sistemas externos em formatos abertos",
                    ),
                ),
                (
                    "art8_3_discloses_data_structure_formats",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Divulga os formatos utilizados na estruturação da informação",
                    ),
                ),
                (
                    "art8_3_ensures_authenticity_integrity",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Garante autenticidade e integridade das informações",
                    ),
                ),
                (
                    "art8_3_periodic_updates",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Atualização periódica"
                    ),
                ),
                (
                    "disclosure_updated_bylaws",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Estatuto Social atualizado"
                    ),
                ),
                (
                    "disclosure_agreements",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Ajustes (Termo de Parceria, Convênio, etc.)",
                    ),
                ),
                (
                    "disclosure_work_plan",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Plano de Trabalho"
                    ),
                ),
                (
                    "disclosure_officers_list",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Relação Nominal dos Dirigentes",
                    ),
                ),
                (
                    "disclosure_service_providers_list",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Lista de prestadores de serviços e valores pagos",
                    ),
                ),
                (
                    "disclosure_individualized_compensation",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Remuneração individualizada de dirigentes e empregados",
                    ),
                ),
                (
                    "disclosure_financial_statements",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Balanços e Demonstrações Contábeis",
                    ),
                ),
                (
                    "disclosure_purchasing_regulation",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Regulamento de Compras"
                    ),
                ),
                (
                    "disclosure_hiring_regulation",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Regulamento de Contratação de Pessoal",
                    ),
                ),
                (
                    "disclosure_sic_statistical_report",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Relatório estatístico de atendimento pelo SIC",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "annual_statement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.annualstatement",
                        verbose_name="Prestação de Contas Anual",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Checklist de Transparência (AUDESP)",
                "verbose_name_plural": "historical Checklists de Transparência (AUDESP)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TransparencyChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "has_website",
                    models.BooleanField(
                        default=False,
                        help_text="Lei Federal nº 12.527/11 (LAI), art. 8º §2º",
                        verbose_name="Mantém Sítio na Internet?",
                    ),
                ),
                (
                    "websites",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Sítios na Internet"
                    ),
                ),
                (
                    "art7_8_1_organizational_structure",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Competência e Estrutura Organizacional",
                    ),
                ),
                (
                    "art7_8_1_contact_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Endereço, e-mail, telefones e horários de atendimento",
                    ),
                ),
                (
                    "art7_8_1_transfer_records",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Registro de repasses ou transferências de recursos financeiros",
                    ),
                ),
                (
                    "art7_8_1_expense_records",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Registros de despesas realizadas com recursos públicos",
                    ),
                ),
                (
                    "art7_8_1_procurement_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Informações sobre contratações de bens e serviços",
                    ),
                ),
                (
                    "art7_8_1_goals_tracking_information",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Informações para acompanhamento de programas/ações/metas",
                    ),
                ),
                (
                    "art7_8_1_faq",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Respostas a perguntas mais frequentes da sociedade",
                    ),
                ),
                (
                    "art7_8_1_audit_results",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Resultado de inspeções, auditorias e prestações de contas",
                    ),
                ),
                (
                    "art8_3_content_search_tool",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Ferramenta de pesquisa de conteúdo",
                    ),
                ),
                (
                    "art8_3_open_format_reports",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Geração de relatórios em formatos eletrônicos abertos",
                    ),
                ),
                (
                    "art8_3_automated_external_access",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Acesso automatizado por sistemas externos em formatos abertos",
                    ),
                ),
                (
                    "art8_3_discloses_data_structure_formats",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Divulga os formatos utilizados na estruturação da informação",
                    ),
                ),
                (
                    "art8_3_ensures_authenticity_integrity",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Garante autenticidade e integridade das informações",
                    ),
                ),
                (
                    "art8_3_periodic_updates",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Atualização periódica"
                    ),
                ),
                (
                    "disclosure_updated_bylaws",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Estatuto Social atualizado"
                    ),
                ),
                (
                    "disclosure_agreements",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Ajustes (Termo de Parceria, Convênio, etc.)",
                    ),
                ),
                (
                    "disclosure_work_plan",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Plano de Trabalho"
                    ),
                ),
                (
                    "disclosure_officers_list",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Relação Nominal dos Dirigentes",
                    ),
                ),
                (
                    "disclosure_service_providers_list",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Lista de prestadores de serviços e valores pagos",
                    ),
                ),
                (
                    "disclosure_individualized_compensation",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Remuneração individualizada de dirigentes e empregados",
                    ),
                ),
                (
                    "disclosure_financial_statements",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Balanços e Demonstrações Contábeis",
                    ),
                ),
                (
                    "disclosure_purchasing_regulation",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Regulamento de Compras"
                    ),
                ),
                (
                    "disclosure_hiring_regulation",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Regulamento de Contratação de Pessoal",
                    ),
                ),
                (
                    "disclosure_sic_statistical_report",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Relatório estatístico de atendimento pelo SIC",
                    ),
                ),
                (
                    "annual_statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transparency_checklist",
                        to="accountability.annualstatement",
                        verbose_name="Prestação de Contas Anual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist de Transparência (AUDESP)",
                "verbose_name_plural": "Checklists de Transparência (AUDESP)",
            },
        ),
    ]
