# Generated by Django 6.0.5 on 2026-07-10 23:19

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_cityhall_audesp_municipality_code_and_more"),
        ("contracts", "0002_contract_audesp_agreement_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudespSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="Exercício")),
                (
                    "ajuste_type",
                    models.CharField(
                        choices=[
                            ("CONTRATO_GESTAO", "Contrato de Gestão"),
                            ("CONVENIO", "Convênio"),
                            ("TERMO_COLABORACAO", "Termo de Colaboração"),
                            ("TERMO_FOMENTO", "Termo de Fomento"),
                            ("TERMO_PARCERIA", "Termo de Parceria"),
                            ("DECLARACAO_NEGATIVA", "Declaração Negativa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ajuste (AUDESP)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("VALID", "Válido"),
                            ("INVALID", "Inválido"),
                            ("SUBMITTED", "Enviado"),
                            ("ACCEPTED", "Aceito"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Último payload construído para este (ajuste, exercício)",
                        verbose_name="Documento JSON",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Erros de validação contra o JSON Schema, se houver",
                        verbose_name="Erros de Validação",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        blank=True,
                        help_text="Preenchido após envio bem-sucedido ao webservice AUDESP",
                        max_length=32,
                        null=True,
                        verbose_name="Número de Protocolo",
                    ),
                ),
                (
                    "built_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Construído em"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audesp_submissions",
                        to="contracts.contract",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissão AUDESP",
                "verbose_name_plural": "Submissões AUDESP",
                "ordering": ("-built_at",),
                "indexes": [
                    models.Index(
                        fields=["contract", "fiscal_year", "-built_at"],
                        name="audesp_aude_contrac_89b4f7_idx",
                    )
                ],
            },
        ),
    ]
