# Generated by Django 6.0.5 on 2026-07-11 12:50

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cityhall_audesp_municipality_code_and_more'),
        ('audesp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudespCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('environment', models.CharField(choices=[('PILOTO', 'Piloto'), ('PRODUCAO', 'Produção')], max_length=8, verbose_name='Ambiente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('city_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audesp_credentials', to='accounts.cityhall', verbose_name='Prefeitura')),
            ],
            options={
                'verbose_name': 'Credencial AUDESP',
                'verbose_name_plural': 'Credenciais AUDESP',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('city_hall', 'environment'), name='unique_audesp_credential_per_city_hall_environment')],
            },
        ),
    ]
