# Generated by Django 6.0.5 on 2026-07-30 23:02

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_expense_encumbrance_value_and_more'),
        ('accounts', '0002_cityhall_audesp_municipality_code_and_more'),
        ('audesp', '0002_audespcredential'),
        ('contracts', '0003_contract_signature_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudespFaseIVSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('AJUSTE', 'Ajuste'), ('EMPENHO', 'Empenho')], max_length=7, verbose_name='Tipo de Documento')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('VALID', 'Válido'), ('INVALID', 'Inválido'), ('SUBMITTED', 'Enviado'), ('ACCEPTED', 'Aceito'), ('REJECTED', 'Rejeitado')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('payload', models.JSONField(help_text='Último payload construído para esta submissão', verbose_name='Documento JSON')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='Erros de validação contra o JSON Schema, se houver', verbose_name='Erros de Validação')),
                ('protocol_number', models.CharField(blank=True, help_text='Preenchido após envio bem-sucedido ao webservice AUDESP', max_length=32, null=True, verbose_name='Número de Protocolo')),
                ('built_at', models.DateTimeField(auto_now_add=True, verbose_name='Construído em')),
                ('budget_commitment', models.ForeignKey(blank=True, help_text='Preenchido apenas quando document_type = EMPENHO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audesp_fase_iv_submissions', to='accountability.budgetcommitment', verbose_name='Empenho')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audesp_fase_iv_submissions', to='contracts.contract', verbose_name='Ajuste')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Submissão AUDESP Fase IV',
                'verbose_name_plural': 'Submissões AUDESP Fase IV',
                'ordering': ('-built_at',),
                'indexes': [models.Index(fields=['contract', 'document_type', '-built_at'], name='audesp_aude_contrac_1ec866_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('budget_commitment__isnull', False), ('document_type', 'EMPENHO')), models.Q(('budget_commitment__isnull', True), ('document_type', 'AJUSTE')), _connector='OR'), name='fase_iv_empenho_requires_budget_commitment')],
            },
        ),
    ]
