# Generated by Django 6.0.5 on 2026-07-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audesp', '0003_audespfaseivsubmission'),
        ('audesp', '0003_audespsubmission_retificacao_and_more'),
    ]

    operations = [
    ]
