# Generated by Django 5.1.4 on 2025-01-24 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hora do registro"
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Email do Usuário",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED_CIVIL_SERVANT", "Criou funcionário público"),
                            ("CREATED_FOLDER_MANAGER", "Criou gestor de pasta"),
                            (
                                "CREATED_ORGANIZATION_ACCOUNTANT",
                                "Criou contador / funcionário organização",
                            ),
                            ("CREATED_ACCOUNTABILITY", "Criou prestação mensal"),
                            ("UPDATED_ACCOUNTABILITY", "Atualizou prestação mensal"),
                            ("CREATED_BANK_ACCOUNT", "Criou conta bancária"),
                            ("UPDATED_BANK_ACCOUNT", "Atualizou conta bancária"),
                            ("UPLOADED_BALANCE_FILE", "subiu extrato bancário"),
                            ("CREATED_COMPANY", "Criou empresa"),
                            ("UPDATED_COMPANY", "Atualizou empresa"),
                            ("CREATED_CONTRACT", "Criou contrato"),
                            ("CREATED_CONTRACT_ADDENDUM", "Criou aditivo de contrato"),
                            ("CREATED_CONTRACT_GOAL", "Cadastrou meta do contrato"),
                            ("UPDATED_CONTRACT_GOAL", "Atualizou meta do contrato"),
                            ("CREATED_CONTRACT_ITEM", "Cadastrou item do contrato"),
                            ("UPDATED_CONTRACT_ITEM", "Atualizou item do contrato"),
                            ("CREATED_EXPENSE", "Cadastrou despesa"),
                            ("UPDATED_EXPENSE", "Atualizou despesa"),
                            ("CREATED_EXPENSE_SOURCE", "Cadastrou fonte de despesa"),
                            ("DELETED_EXPENSE_SOURCE", "Apagou fonte de despesa"),
                            ("CREATED_REVENUE", "Cadastrou receita"),
                            ("UPDATED_REVENUE", "Atualizou receita"),
                            ("CREATED_REVENUE_SOURCE", "Cadastrou fonte de recurso"),
                            ("DELETED_REVENUE_SOURCE", "Apagou fonte de recurso"),
                        ],
                        max_length=32,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="ID do alvo"
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type do alvo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Atividade",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user_email", "action"],
                        name="activity_ac_user_em_ac3c4d_idx",
                    )
                ],
            },
        ),
    ]
