# Generated by Django 5.1.4 on 2024-12-29 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hora do registro"
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Email do Usuário",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_CIVIL_SERVANT", "criou funcionário público"),
                            ("CREATE_FOLDER_MANAGER", "criou gestor de pasta"),
                            (
                                "CREATE_ONG_ACCOUNTANT",
                                "criou contador / funcionário ong",
                            ),
                            ("CREATE_CONTRACT", "criou contrato"),
                            ("CREATED_ACCOUNTABILITY", "criou contabilidade mês"),
                        ],
                        max_length=32,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="ID do alvo"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type do alvo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Atividade",
            },
        ),
    ]
