# Generated by Django 6.0.5 on 2026-05-14 00:14

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name=django.db.models.fields.UUIDField)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em:')),
                ('category', models.CharField(choices=[('ACCOUNTABILITY_CREATED', 'Uma nova prestação foi criada'), ('ACCOUNTABILITY_ANALISYS', 'Prestação enviada para análise'), ('ACCOUNTABILITY_CORRECTING', 'Prestação enviada para correção'), ('ACCOUNTABILITY_FINISHED', 'Prestação marcada como finalizada'), ('CONTRACT_CREATED', 'Um novo contrato foi criado'), ('CONTRACT_STATUS', 'O Status do contrato foi atualizado'), ('CONTRACT_GOAL_COMMENTED', 'Meta do contrato comentada'), ('CONTRACT_ITEM_COMMENTED', 'Item do contrato comentada'), ('CONTRACT_ITEM_VALUE_REQUESTED', 'Pedido de remanejamento de gastos feito'), ('CONTRACT_ITEM_VALUE_REVIEWED', 'Pedido de remanejamento de gastos revisado'), ('EXECUTION_ANALISYS', 'Execução enviada para análise'), ('EXECUTION_CORRECTING', 'Execução enviada para correção'), ('EXECUTION_FINISHED', 'Execução marcada como finalizada')], max_length=32, verbose_name='Categoria')),
                ('object_id', models.UUIDField(verbose_name='ID do objeto')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora do registro')),
                ('user_email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email do Usuário')),
                ('action', models.CharField(choices=[('CREATED_CIVIL_SERVANT', 'Cadastrou funcionário público'), ('UPDATED_CIVIL_SERVANT', 'Atualizou funcionário público'), ('DELETED_CIVIL_SERVANT', 'Deletou funcionário público'), ('CREATED_FOLDER_MANAGER', 'Cadastrou gestor de pasta'), ('UPDATED_FOLDER_MANAGER', 'Atualizou gestor de pasta'), ('DELETED_FOLDER_MANAGER', 'Deletou gestor de pasta'), ('ACTIVATED_FOLDER_MANAGER', 'Ativou gestor de pasta'), ('DESACTIVATED_FOLDER_MANAGER', 'Desativou gestor de pasta'), ('CREATED_ORGANIZATION_ACCOUNTANT', 'Cadastrou contador / funcionário da organização'), ('UPDATED_ORGANIZATION_ACCOUNTANT', 'Atualizou contador / funcionário da organização'), ('DELETED_ORGANIZATION_ACCOUNTANT', 'Deletou contador / funcionário da organização'), ('ACTIVATED_ORGANIZATION_ACCOUNTANT', 'Ativou contador / funcionário da organização'), ('DESACTIVATED_ORGANIZATION_ACCOUNTANT', 'Desativou contador / funcionário da organização'), ('CREATED_ORGANIZATION_COMMITTEE', 'Cadastrou membro do comitê'), ('UPDATED_ORGANIZATION_COMMITTEE', 'Atualizou membro do comitê'), ('DELETED_ORGANIZATION_COMMITTEE', 'Deletou membro do comitê'), ('ACTIVATED_ORGANIZATION_COMMITTEE', 'Ativou membro do comitê'), ('DESACTIVATED_ORGANIZATION_COMMITTEE', 'Desativou membro do comitê'), ('CREATED_ACCOUNTABILITY', 'Criou prestação mensal'), ('CREATED_ACCOUNTABILITY_FILE', 'Subiu documento de prestação'), ('DELETED_ACCOUNTABILITY_FILE', 'Deletou documento de prestação'), ('SENT_TO_ANALISYS', 'Enviou para análise'), ('SENT_TO_CORRECT', 'Enviou para correção'), ('MARKED_AS_FINISHED', 'Marcou como finalizada'), ('IMPORTED_ACCOUNTABILITY_FILE', 'Importou arquivo de prestação'), ('UPLOADED_EXPENSE_FILE', 'Subiu arquivo de despesa'), ('UPLOADED_REVENUE_FILE', 'Subiu arquivo de receita'), ('DELETED_EXPENSE_FILE', 'Deletou arquivo de despesa'), ('DELETED_REVENUE_FILE', 'Deletou arquivo de receita'), ('CREATED_BANK_ACCOUNT', 'Criou conta bancária'), ('UPDATED_BANK_ACCOUNT', 'Atualizou conta bancária'), ('UPLOADED_BALANCE_FILE', 'subiu extrato bancário'), ('CREATED_COMPANY', 'Criou empresa'), ('UPDATED_COMPANY', 'Atualizou empresa'), ('CREATED_CONTRACT', 'Criou contrato'), ('CREATED_CONTRACT_ADDENDUM', 'Criou aditivo de contrato'), ('UPDATED_CONTRACT_ADDENDUM', 'Atualizou aditivo de contrato'), ('CREATED_CONTRACT_DOCUMENT', 'Criou documento de contrato'), ('UPDATED_CONTRACT_DOCUMENT', 'Atualizou documento de contrato'), ('UPDATED_CONTRACT_STATUS', 'Atualizou status do contrato'), ('CREATED_CONTRACT_INTERESTED', 'Cadastrou interessado no contrato'), ('UPDATED_CONTRACT_INTERESTED', 'Atualizou interessado no contrato'), ('DELETED_CONTRACT_INTERESTED', 'Deletou interessado no contrato'), ('UPDATED_CONTRACT_MONTH_TRASNFER', 'Atualizou repasse mensal'), ('CREATED_CONTRACT_GOAL', 'Cadastrou meta do contrato'), ('COMMENTED_CONTRACT_GOAL', 'Comentou meta do contrato'), ('UPDATED_CONTRACT_GOAL', 'Atualizou meta do contrato'), ('CREATED_CONTRACT_ITEM', 'Cadastrou item do contrato'), ('COMMENTED_CONTRACT_ITEM', 'Comentou item do contrato'), ('UPDATED_CONTRACT_ITEM', 'Atualizou item do contrato'), ('REQUEST_NEW_VALUE_ITEM', 'Solicitou nova valor do item'), ('ANALISED_NEW_VALUE_ITEM', 'Analisou pedido de novo valor do item'), ('CREATED_CONTRACT_ITEM_SUPPLEMENT', 'Cadastrou suplemento de item'), ('UPDATED_CONTRACT_ITEM_SUPPLEMENT', 'Atualizou suplemento de item'), ('DELETED_CONTRACT_ITEM_SUPPLEMENT', 'Deletou suplemento de item'), ('UPLOADED_CONTRACT_ITEM_PURCHASE_FILE', 'Subiu arquivo de compra de item'), ('DELETED_CONTRACT_ITEM_PURCHASE_FILE', 'Deletou arquivo de compra de item'), ('CREATED_CONTRACT_EXECUTION', 'Criou relatório de execução'), ('EXECUTION_TO_ANALISYS', 'Enviou relatório para análise'), ('EXECUTION_SENT_TO_CORRECT', 'Enviou relatório para correção'), ('EXECUTION_MARKED_AS_FINISHED', 'Marcou relatório como finalizada'), ('CREATED_EXECUTION_ACTIVITY', 'Criou Atividade Executada'), ('UPDATED_EXECUTION_ACTIVITY', 'Atualizou Atividade Executada'), ('CREATED_EXECUTION_FILE', 'Anexou Arquivo de Atividade'), ('UPDATED_EXECUTION_FILE', 'Atualizou Arquivo de Atividade'), ('CREATED_EXPENSE', 'Cadastrou despesa'), ('UPDATED_EXPENSE', 'Atualizou despesa'), ('GLOSSED_EXPENSE', 'Glosou despesa'), ('RECONCILED_EXPENSE', 'Conciliou despesa'), ('REVIEWED_EXPENSE', 'Revisou despesa'), ('DUPLICATED_EXPENSE', 'Duplicou despesa'), ('DELETED_EXPENSE', 'Deletou despesa'), ('CREATED_FAVORED', 'Cadastrou favorecido'), ('UPDATED_FAVORED', 'Atualizou favorecido'), ('DELETED_FAVORED', 'Apagou favorecido'), ('CREATED_RESOURCES_SOURCE', 'Cadastrou fonte de recurso'), ('UPDATED_RESOURCES_SOURCE', 'Atualizou fonte de recurso'), ('DELETED_RESOURCES_SOURCE', 'Apagou fonte de recurso'), ('CREATED_REVENUE', 'Cadastrou receita'), ('UPDATED_REVENUE', 'Atualizou receita'), ('RECONCILED_REVENUE', 'Conciliou receita'), ('REVIEWED_REVENUE', 'Revisou receita'), ('DUPLICATED_REVENUE', 'Duplicou receita'), ('DELETED_REVENUE', 'Deletou receita')], max_length=128, verbose_name='Ação')),
                ('target_object_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID do alvo')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type do alvo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividade',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user_email', 'action'], name='activity_ac_user_em_ac3c4d_idx')],
            },
        ),
    ]
