# Generated by Django 5.1.4 on 2024-12-29 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Registro de Atividade",
            },
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "criou gestor de pasta"),
                    ("CREATED_ONG_ACCOUNTANT", "criou contador / funcionário ong"),
                    ("CREATED_CONTRACT", "criou contrato"),
                    ("CREATED_ACCOUNTABILITY", "criou contabilidade mês"),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user_email", "action"], name="activity_ac_user_em_ac3c4d_idx"
            ),
        ),
    ]
