# Generated by Django 5.1.4 on 2025-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "Criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "Criou gestor de pasta"),
                    (
                        "CREATED_ORGANIZATION_ACCOUNTANT",
                        "Criou contador / funcionário organização",
                    ),
                    ("CREATED_ACCOUNTABILITY", "Criou prestação mensal"),
                    ("UPDATED_ACCOUNTABILITY", "Atualizou prestação mensal"),
                    ("CREATED_BANK_ACCOUNT", "Criou conta bancária"),
                    ("UPDATED_BANK_ACCOUNT", "Atualizou conta bancária"),
                    ("UPLOADED_BALANCE_FILE", "subiu extrato bancário"),
                    ("CREATED_COMPANY", "Criou empresa"),
                    ("UPDATED_COMPANY", "Atualizou empresa"),
                    ("CREATED_CONTRACT", "Criou contrato"),
                    ("CREATED_CONTRACT_ADDENDUM", "Criou aditivo de contrato"),
                    ("CREATED_CONTRACT_GOAL", "Criou meta do contrato"),
                    ("UPDATED_CONTRACT_GOAL", "Atualizou meta do contrato"),
                    ("CREATED_CONTRACT_ITEM", "Criou item do contrato"),
                    ("UPDATED_CONTRACT_ITEM", "Atualizou item do contrato"),
                    ("CREATE_EXPENSE_SOURCE", "Criou fonte de despesa"),
                    ("DELETED_EXPENSE_SOURCE", "Apagou fonte de despesa"),
                    ("CREATE_REVENUE_SOURCE", "Criou fonte de recurso"),
                    ("DELETED_REVENUE_SOURCE", "Apagou fonte de recurso"),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
    ]
