# Generated by Django 5.1.6 on 2025-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_alter_activitylog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[("CONTRACT_CREATED", "Um novo contrato foi criado")],
                max_length=16,
                verbose_name="Categoria",
            ),
        ),
    ]
