# Generated by Django 5.1.4 on 2024-12-30 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "activity",
            "0002_alter_activitylog_options_alter_activitylog_action_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="created",
        ),
    ]
