# Generated by Django 5.1.4 on 2025-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "Criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "Criou gestor de pasta"),
                    (
                        "CREATED_ORGANIZATION_ACCOUNTANT",
                        "Criou contador / funcionário organização",
                    ),
                    ("CREATED_ACCOUNTABILITY", "Criou prestação mensal"),
                    ("UPDATED_ACCOUNTABILITY", "Atualizou prestação mensal"),
                    ("CREATED_BANK_ACCOUNT", "Criou conta bancária"),
                    ("UPDATED_BANK_ACCOUNT", "Atualizou conta bancária"),
                    ("UPLOADED_BALANCE_FILE", "subiu extrato bancário"),
                    ("CREATED_COMPANY", "Criou empresa"),
                    ("UPDATED_COMPANY", "Atualizou empresa"),
                    ("CREATED_CONTRACT", "Criou contrato"),
                    ("CREATED_CONTRACT_ADDENDUM", "Criou aditivo de contrato"),
                    ("CREATED_CONTRACT_GOAL", "Cadastrou meta do contrato"),
                    ("COMMENTED_CONTRACT_GOAL", "Comentou meta do contrato"),
                    ("UPDATED_CONTRACT_GOAL", "Atualizou meta do contrato"),
                    ("CREATED_CONTRACT_ITEM", "Cadastrou item do contrato"),
                    ("COMMENTED_CONTRACT_ITEM", "Comentou item do contrato"),
                    ("UPDATED_CONTRACT_ITEM", "Atualizou item do contrato"),
                    ("CREATED_CONTRACT_EXECUTION", "Criou Relatório de Execução"),
                    ("CREATED_EXECUTION_ACTIVITY", "Criou Atividade Executada"),
                    ("UPDATED_EXECUTION_ACTIVITY", "Atualizou Atividade Executada"),
                    ("CREATED_EXPENSE", "Cadastrou despesa"),
                    ("UPDATED_EXPENSE", "Atualizou despesa"),
                    ("CREATED_FAVORED", "Cadastrou favorecido"),
                    ("UPDATED_FAVORED", "Atualizou favorecido"),
                    ("DELETED_FAVORED", "Apagou favorecido"),
                    ("CREATED_RESOURCES_SOURCE", "Cadastrou fonte de recurso"),
                    ("DELETED_RESOURCES_SOURCE", "Apagou fonte de recurso"),
                    ("CREATED_REVENUE", "Cadastrou receita"),
                    ("UPDATED_REVENUE", "Atualizou receita"),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
    ]
