# Generated by Django 5.1.6 on 2025-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_alter_notification_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "ACCOUNTABILITY_CREATED",
                        "Uma nova prestação foi criada",
                    ),
                    ("CONTRACT_CREATED", "Um novo contrato foi criado"),
                ],
                max_length=32,
                verbose_name="Categoria",
            ),
        ),
    ]
