# Generated by Django 5.1.6 on 2025-02-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0004_alter_notification_category"),
    ]

    operations = [
        migrations.DeleteModel(name="Notification",),
    ]
