# Generated by Django 5.1.4 on 2025-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "criou gestor de pasta"),
                    ("CREATED_ONG_ACCOUNTANT", "criou contador / funcionário ong"),
                    ("CREATED_ACCOUNTABILITY", "criou contabilidade mês"),
                    ("CREATED_CONTRACT", "criou contrato"),
                    ("CREATED_CONTRACT_ADDENDUM", "criou aditivo de contrato"),
                    ("CREATED_CONTRACT_ITEM", "criou item do contrato"),
                    ("CREATED_CONTRACT_GOAL", "criou meta do contrato"),
                    ("CREATE_EXPENSE_SOURCE", "criou fonte de despesa"),
                    ("DELETED_EXPENSE_SOURCE", "apagou fonte de despesa"),
                    ("CREATE_REVENUE_SOURCE", "criou fonte de recurso"),
                    ("DELETED_REVENUE_SOURCE", "apagou fonte de recurso"),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
    ]
