# Generated by Django 5.1.6 on 2025-02-26 17:26

import django.db.models.deletion
import django.db.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_delete_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lida em:"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCOUNTABILITY_CREATED", "Uma nova prestação foi criada"),
                            (
                                "ACCOUNTABILITY_ANALISYS",
                                "Prestação enviada para análise",
                            ),
                            (
                                "ACCOUNTABILITY_CORRECTING",
                                "Prestação enviada para correção",
                            ),
                            (
                                "ACCOUNTABILITY_FINISHED",
                                "Prestação marcada como finalizada",
                            ),
                            ("CONTRACT_CREATED", "Um novo contrato foi criado"),
                            ("CONTRACT_STATUS", "O Status do contrato foi atualizado"),
                            ("CONTRACT_GOAL_COMMENTED", "Meta do contrato comentada"),
                            ("CONTRACT_ITEM_COMMENTED", "Item do contrato comentada"),
                            (
                                "CONTRACT_ITEM_VALUE_REQUESTED",
                                "Pedido de remanejamento de gastos feito",
                            ),
                            (
                                "CONTRACT_ITEM_VALUE_REVIEWED",
                                "Pedido de remanejamento de gastos revisado",
                            ),
                        ],
                        max_length=32,
                        verbose_name="Categoria",
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="ID do objeto")),
                ("text", models.CharField(max_length=255, verbose_name="Texto")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
    ]
