# Generated by Django 5.1.6 on 2025-03-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0006_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "Criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "Criou gestor de pasta"),
                    (
                        "CREATED_ORGANIZATION_ACCOUNTANT",
                        "Criou contador / funcionário organização",
                    ),
                    ("CREATED_ACCOUNTABILITY", "Criou prestação mensal"),
                    ("SENT_TO_ANALISYS", "Enviou para análise"),
                    ("SENT_TO_CORRECT", "Enviou para correção"),
                    ("MARKED_AS_FINISHED", "Marcou como finalizada"),
                    ("CREATED_BANK_ACCOUNT", "Criou conta bancária"),
                    ("UPDATED_BANK_ACCOUNT", "Atualizou conta bancária"),
                    ("UPLOADED_BALANCE_FILE", "subiu extrato bancário"),
                    ("CREATED_COMPANY", "Criou empresa"),
                    ("UPDATED_COMPANY", "Atualizou empresa"),
                    ("CREATED_CONTRACT", "Criou contrato"),
                    ("CREATED_CONTRACT_ADDENDUM", "Criou aditivo de contrato"),
                    (
                        "UPDATED_CONTRACT_STATUS",
                        "Atualizou status do contrato",
                    ),
                    ("CREATED_CONTRACT_GOAL", "Cadastrou meta do contrato"),
                    ("COMMENTED_CONTRACT_GOAL", "Comentou meta do contrato"),
                    ("UPDATED_CONTRACT_GOAL", "Atualizou meta do contrato"),
                    ("CREATED_CONTRACT_ITEM", "Cadastrou item do contrato"),
                    ("COMMENTED_CONTRACT_ITEM", "Comentou item do contrato"),
                    ("UPDATED_CONTRACT_ITEM", "Atualizou item do contrato"),
                    ("REQUEST_NEW_VALUE_ITEM", "Solicitou nova valor do item"),
                    (
                        "ANALISED_NEW_VALUE_ITEM",
                        "Analisou pedido de novo valor do item",
                    ),
                    (
                        "CREATED_CONTRACT_EXECUTION",
                        "Criou relatório de execução",
                    ),
                    ("EXECUTION_TO_ANALISYS", "Enviou relatório para análise"),
                    (
                        "EXECUTION_SENT_TO_CORRECT",
                        "Enviou relatório para correção",
                    ),
                    (
                        "EXECUTION_MARKED_AS_FINISHED",
                        "Marcou relatório como finalizada",
                    ),
                    (
                        "CREATED_EXECUTION_ACTIVITY",
                        "Criou Atividade Executada",
                    ),
                    (
                        "UPDATED_EXECUTION_ACTIVITY",
                        "Atualizou Atividade Executada",
                    ),
                    ("CREATED_EXECUTION_FILE", "Anexou Arquivo de Atividade"),
                    (
                        "UPDATED_EXECUTION_FILE",
                        "Atualizou Arquivo de Atividade",
                    ),
                    ("CREATED_EXPENSE", "Cadastrou despesa"),
                    ("UPDATED_EXPENSE", "Atualizou despesa"),
                    ("GLOSSED_EXPENSE", "Glosou despesa"),
                    ("RECONCILED_EXPENSE", "Conciliou despesa"),
                    ("REVIEWED_EXPENSE", "Revisou despesa"),
                    ("DUPLICATED_EXPENSE", "Duplicou despesa"),
                    ("DELETED_EXPENSE", "Deletou despesa"),
                    ("CREATED_FAVORED", "Cadastrou favorecido"),
                    ("UPDATED_FAVORED", "Atualizou favorecido"),
                    ("DELETED_FAVORED", "Apagou favorecido"),
                    ("CREATED_RESOURCES_SOURCE", "Cadastrou fonte de recurso"),
                    ("DELETED_RESOURCES_SOURCE", "Apagou fonte de recurso"),
                    ("CREATED_REVENUE", "Cadastrou receita"),
                    ("UPDATED_REVENUE", "Atualizou receita"),
                    ("RECONCILED_REVENUE", "Conciliou receita"),
                    ("REVIEWED_REVENUE", "Revisou receita"),
                    ("DUPLICATED_REVENUE", "Duplicou receita"),
                    ("DELETED_REVENUE", "Deletou receita"),
                ],
                max_length=128,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "ACCOUNTABILITY_CREATED",
                        "Uma nova prestação foi criada",
                    ),
                    (
                        "ACCOUNTABILITY_ANALISYS",
                        "Prestação enviada para análise",
                    ),
                    (
                        "ACCOUNTABILITY_CORRECTING",
                        "Prestação enviada para correção",
                    ),
                    (
                        "ACCOUNTABILITY_FINISHED",
                        "Prestação marcada como finalizada",
                    ),
                    ("CONTRACT_CREATED", "Um novo contrato foi criado"),
                    ("CONTRACT_STATUS", "O Status do contrato foi atualizado"),
                    ("CONTRACT_GOAL_COMMENTED", "Meta do contrato comentada"),
                    ("CONTRACT_ITEM_COMMENTED", "Item do contrato comentada"),
                    (
                        "CONTRACT_ITEM_VALUE_REQUESTED",
                        "Pedido de remanejamento de gastos feito",
                    ),
                    (
                        "CONTRACT_ITEM_VALUE_REVIEWED",
                        "Pedido de remanejamento de gastos revisado",
                    ),
                    ("EXECUTION_ANALISYS", "Execução enviada para análise"),
                    ("EXECUTION_CORRECTING", "Execução enviada para correção"),
                    ("EXECUTION_FINISHED", "Execução marcada como finalizada"),
                ],
                max_length=32,
                verbose_name="Categoria",
            ),
        ),
    ]
