# Generated by Django 5.1.4 on 2025-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0007_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED_CIVIL_SERVANT", "criou funcionário público"),
                    ("CREATED_FOLDER_MANAGER", "criou gestor de pasta"),
                    ("CREATED_ONG_ACCOUNTANT", "criou contador / funcionário ong"),
                    ("CREATED_ACCOUNTABILITY", "criou contabilidade mês"),
                    ("UPDATED_ACCOUNTABILITY", "atualizou contabilidade mês"),
                    ("CREATED_BANK_ACCOUNT", "criou conta bancária"),
                    ("UPDATED_BANK_ACCOUNT", "atualizou conta bancária"),
                    ("UPLOADED_BALANCE_FILE", "subiu extrato bancário"),
                    ("CREATED_CONTRACT", "criou contrato"),
                    ("CREATED_CONTRACT_ADDENDUM", "criou aditivo de contrato"),
                    ("CREATED_CONTRACT_GOAL", "criou meta do contrato"),
                    ("UPDATED_CONTRACT_GOAL", "atualizou meta do contrato"),
                    ("CREATED_CONTRACT_ITEM", "criou item do contrato"),
                    ("UPDATED_CONTRACT_ITEM", "atualizou item do contrato"),
                    ("CREATE_EXPENSE_SOURCE", "criou fonte de despesa"),
                    ("DELETED_EXPENSE_SOURCE", "apagou fonte de despesa"),
                    ("CREATE_REVENUE_SOURCE", "criou fonte de recurso"),
                    ("DELETED_REVENUE_SOURCE", "apagou fonte de recurso"),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
    ]
