# Generated by Django 5.1.6 on 2025-03-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_organizationtenantbaseclass"),
        ("activity", "0012_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organization",
            ),
        ),
    ]
