# Generated by Django 5.1.6 on 2025-03-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_delete_organizationtenantbaseclass"),
        (
            "activity",
            "0013_activitylog_organization_notification_organization",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
    ]
