# Generated by Django 5.1.4 on 2025-02-16 13:06

import uuid

import django.db.models.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accountability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                ("year", models.IntegerField(default=0, verbose_name="Ano")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIP", "Em Andamento"),
                            ("SENT", "Enviada para análise"),
                            ("CORRECTING", "Corrigindo"),
                            ("FINISHED", "Finalizada"),
                        ],
                        default="WIP",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestação",
                "verbose_name_plural": "Prestações",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_ANALISIS", "Em Análise"),
                            ("REJECTED", "Rejeitada"),
                            ("APPROVED", "Aprovada"),
                        ],
                        default="IN_ANALISIS",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pendencies",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pendências"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Pago?")),
                (
                    "conciled",
                    models.BooleanField(default=False, verbose_name="Conciliado?"),
                ),
                (
                    "planned",
                    models.BooleanField(default=True, verbose_name="Planejado?"),
                ),
                (
                    "identification",
                    models.CharField(
                        max_length=128, verbose_name="Identificação da Despesa"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "PERMANENT_GOODS_AND_MATERIALS",
                                "Bens e Materiais permanentes",
                            ),
                            (
                                "COMPUTER_GOODS_AND_EQUIPMENT",
                                "Bens e equipamentos de informática",
                            ),
                            (
                                "HOSPITAL_GOODS_AND_EQUIPMENT",
                                "Bens e equipamentos hospitalares",
                            ),
                            ("FUEL", "Combustível"),
                            ("BANKING_EXPENSES", "Despesas bancárias"),
                            ("BANKING_IOF", "IOF"),
                            ("BANKING_IRRF", "IRRF"),
                            ("INTEREST", "Juros"),
                            ("FOODSTUFFS", "Gêneros Alimentícios"),
                            ("REAL_ESTATE_LEASE", "Locação de Imóveis"),
                            ("AMBULANCES", "Ambulâncias"),
                            ("COMPUTER_EQUIPMENT", "Equipamento de informática"),
                            (
                                "HOSPITCAL_MEDICAL_EQUIPMENT",
                                "Equipamento médico hospitalar",
                            ),
                            ("LAUNDRY_LINEN", "Lavanderia e enxoval"),
                            ("CAR_LEASE", "Locação de Carro"),
                            ("MISCELLANOUS_LEASES", "Locações Diversas"),
                            ("SOFTWARE_SYSTEM", "Sistema de software"),
                            (
                                "MEDICAL_HOSPITAL_SUPPLIES",
                                "Material Médico e Hospitalar",
                            ),
                            ("MEDICINES", "Medicamentos"),
                            ("WORKS", "Obras"),
                            (
                                "OTHER_ADMINISTRATIVE_EXPENSES",
                                "Despesas Administrativas",
                            ),
                            (
                                "RETURN_OF_FUNDS",
                                "Devolução de Recurso ao Órgão Concedente",
                            ),
                            ("PARKING_DRIVING_TAXI", "Estacionamento/condução/táxi"),
                            ("IPTU", "IPTU"),
                            (
                                "TAXES_FEES_CONTRIBUTIONS",
                                "Impostos, Taxas e Contribuições",
                            ),
                            ("OTHER_EXPENSES", "Outras despesas - Diversos"),
                            ("INSURANCE", "Seguros"),
                            ("TRAVEL_TICKET_STAY", "Viagens (passagem, hospedagem)"),
                            ("COOKING_GAS", "Gás de Cozinha"),
                            ("COMPUTER_SUPPLIES", "Materiais de Informática"),
                            (
                                "MATERIALS_FOR_SMALL_REPAIRS",
                                "Materiais para Pequenos Reparos",
                            ),
                            ("EDUCATIONAL_MATERIAL", "Material Pedagógico"),
                            (
                                "HYGIENE_CLEANING_SUPPLIES_UNIFORMS",
                                "Material de Higiene/Limpeza/Uniformes",
                            ),
                            ("SPORTS_EQUIPMENTS", "Material esportivo"),
                            ("UTENSILS", "Utensílios"),
                            ("OFFICE_SUPPLIES_1", "Materiais de Expediente"),
                            ("OFFICE_SUPPLIES_2", "Material de Escritório"),
                            (
                                "OFFICE_SUPPLIES_3",
                                "Material de expediente/correio/fotocópias",
                            ),
                            ("OTHER_CONSUMABLES", "Outros Materiais de Consumo"),
                            ("COMMON_WASTE_COLLECT", "Coleta de lixo comum"),
                            ("HOSPITAL_WASTE_COLLECT", "Coleta de lixo hospitalar"),
                            (
                                "CONSULTING_LEGAL_ADVICE",
                                "Consultoria/assessoria jurídica",
                            ),
                            ("CLEANING_MAINTENANCE", "Limpeza e conservação"),
                            (
                                "MAINTENANCE_HOSPITAL_EQUIPMENT",
                                "Manutenção - Equipamento Médico Hospitalar",
                            ),
                            (
                                "MAINTENANCE_COMPUTER_EQUIPMENT",
                                "Manutenção - Equipamento de Informática",
                            ),
                            (
                                "MAINTENANCE_BUILDING",
                                "Manutenção - predial e Imobiliário",
                            ),
                            ("MAINTENANCE_VEHICLE", "Manutenção de veículos"),
                            ("CONSTRUCTION", "Obras"),
                            ("MAINTENANCE_OTHERS", "Outras Manutenções"),
                            (
                                "LEGAL_THIRD_PARTY_SERVICES",
                                "Outros serviços de terceiros pessoa jurídica",
                            ),
                            ("ADVERTISING_PUBILICITY", "Publicidade e propaganda"),
                            (
                                "THERAPEUTIC_SUPPORT_SERVICE",
                                "Serviço de apoio diagnóstico terapêutico (sadt)",
                            ),
                            ("SERVICES_ACCOUNTING", "Serviços Contábeis"),
                            ("SERVICES_AUDITING", "Serviços de auditoria"),
                            (
                                "SERVIECS_IT",
                                "Serviços de tecnologia da informação (TI)",
                            ),
                            ("SERVICES_SURVEILLANCES", "Vigilância"),
                            ("THIRTHEENTH_SALARY", "13º Salário"),
                            ("APPRENTICES", "Aprendizes"),
                            ("MEDICAL_ASSISTENCE", "Assistência médica"),
                            ("ADVANCE_NOTICE", "Aviso prévio"),
                            ("BENEFITS", "Benefícios"),
                            ("INTERNSHIP_ALLOWANCE", "Bolsa Auxílio - estagiários"),
                            (
                                "INSS_CONTRIBUTION_SHARE",
                                "Contribuição ao INSS - Cota Patronal",
                            ),
                            ("PIS_CONTRIBUTION", "Contribuição ao PIS"),
                            ("SOCIAL_CONTRIBUTIONS", "Contribuições Sociais"),
                            (
                                "COURSES_TRAINING_RETRAINING",
                                "Cursos/treinamento/reciclagem",
                            ),
                            ("PERSONNEL_EXPENSES", "Despesas com Pessoal"),
                            ("COLLECTIVE_BARGAINING", "Dissídio coletivo"),
                            ("SOCIAL_CHARGES", "Encargos Sociais"),
                            ("FGTS", "FGTS"),
                            ("RESERVE_FUND", "Fundo de Reserva"),
                            ("VACATIONS", "Férias"),
                            ("BONUSES", "Gratificações"),
                            ("HR_INSS", "INSS"),
                            ("HR_IRRF", "IRRF"),
                            ("COMPENSATIONS", "Indenizações"),
                            (
                                "TERMINATION_EMPLOYMENT_CONTRACT",
                                "Rescisão de Contrato de Trabalho - TRCT",
                            ),
                            ("MISCELLANOUS_WITHHOLDINGS", "Retenções Diversas"),
                            (
                                "MANAGEMENT_SALARY",
                                "Salário diretoria (salários e ordenados)",
                            ),
                            (
                                "SALARIES_AND_WAGES",
                                "Salários e ordenados (exceto diretoria)",
                            ),
                            ("UNIFORMS", "Uniformes"),
                            ("FOOD_VOUCHERS", "Vale Alimentação"),
                            ("MEAL_VOUCHERS", "Vale Refeição"),
                            ("TRANSPORTATION_VOUCHERS", "Vale Transporte"),
                            ("INTERN_REMUNERATION", "Remuneração de Estagiários"),
                            (
                                "SERVICES_PF_THIRD_PARTIES",
                                "Serviços Prestados por Terceiro - PF",
                            ),
                            (
                                "SERVICES_PJ_THIRD_PARTIES",
                                "Serviços Prestados por Terceiro - PJ",
                            ),
                            ("MEDICAL_SERVICES", "Serviços médicos (*)"),
                            (
                                "MEDICAL_SERVICES_FOR_INDIVIDUALS",
                                "Serviços médicos pessoa física",
                            ),
                            (
                                "MEDICAL_SERVICES_FOR_ENTITIES",
                                "Serviços médicos pessoa jurídica",
                            ),
                            (
                                "PUBLIC_ADMINISTRATIVE_EXPENSES",
                                "Despesas Administrativas",
                            ),
                            ("ELECTRICITY", "Energia Elétrica"),
                            ("INTERNET_TV", "Internet/TV a cabo"),
                            ("TELEPHONE", "Telefone"),
                            ("PUBLIC_UTILITIES", "Utilidade Publica"),
                            ("WATER_SEWAGE", "Água e Esgoto"),
                        ],
                        max_length=34,
                        null=True,
                        verbose_name="Natureza da Despesa",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Vencimento"),
                ),
                ("competency", models.DateField(verbose_name="Competência")),
                (
                    "liquidation",
                    models.DateField(blank=True, null=True, verbose_name="Liquidação"),
                ),
                (
                    "liquidation_form",
                    models.CharField(
                        choices=[
                            ("BILL", "Boleto"),
                            ("CHECK", "Cheque"),
                            ("DEBIT_CREDIT_CARD", "Cartão Débito/Crédito"),
                            ("DIRECT_DEBIT", "Débito em Conta"),
                            ("ELETRONIC_TRANSFER", "Transferência Eletrônica"),
                            ("MONEY", "Dinheiro"),
                            ("OBTV", "OBTV"),
                        ],
                        default="ELETRONIC_TRANSFER",
                        max_length=18,
                        verbose_name="Forma de Liquidação",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSURANCE_POLICY", "Apolice de Seguro"),
                            ("DEBIT_NOTICE", "Aviso de Débito"),
                            ("PAY_SLIP", "Boleto"),
                            ("TAX_RECEIPT", "Cupom Fiscal"),
                            ("DARF", "DARF"),
                            ("INVOICE", "Fatura"),
                            ("GPS", "GPS"),
                            ("GRCS_DOC", "GRCS ou DOC"),
                            ("GRF", "GRF"),
                            ("GRRF", "GRRF"),
                            ("PAYSLIP", "Holerite"),
                            ("NF", "NF"),
                            ("NFE", "NF-E"),
                            ("NFS", "NFS"),
                            ("NFSE", "NFS-E"),
                            (
                                "NF_INVOICES",
                                "Notas Fiscais (Eletronica, Serviços, etc)",
                            ),
                            ("OTHERS", "Outros"),
                            ("RECEIPT", "Recibo"),
                            ("VACATION_RECEIPT", "Recibo de Férias"),
                            ("RPA", "RPA"),
                            ("TERMINATION_AGREEMENT", "Termo de Rescisão"),
                        ],
                        max_length=21,
                        null=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Número do documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
        migrations.CreateModel(
            name="ExpenseAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                (
                    "comments",
                    models.CharField(max_length=256, verbose_name="Comentários"),
                ),
                (
                    "pending",
                    models.CharField(max_length=256, verbose_name="Pendências"),
                ),
            ],
            options={
                "verbose_name": "Análise de Despesa",
                "verbose_name_plural": "Análise de Despesas",
            },
        ),
        migrations.CreateModel(
            name="ExpenseFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/expenses/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Despesa",
                "verbose_name_plural": "Arquivo de Despesas",
            },
        ),
        migrations.CreateModel(
            name="Favored",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nome")),
                (
                    "document",
                    models.IntegerField(blank=True, null=True, verbose_name="CPF/CNPJ"),
                ),
            ],
            options={
                "verbose_name": "Favorecido",
                "verbose_name_plural": "Favorecidos",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAccountability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                ("year", models.IntegerField(default=0, verbose_name="Ano")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIP", "Em Andamento"),
                            ("SENT", "Enviada para análise"),
                            ("CORRECTING", "Corrigindo"),
                            ("FINISHED", "Finalizada"),
                        ],
                        default="WIP",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prestação",
                "verbose_name_plural": "historical Prestações",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_ANALISIS", "Em Análise"),
                            ("REJECTED", "Rejeitada"),
                            ("APPROVED", "Aprovada"),
                        ],
                        default="IN_ANALISIS",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pendencies",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pendências"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Pago?")),
                (
                    "conciled",
                    models.BooleanField(default=False, verbose_name="Conciliado?"),
                ),
                (
                    "planned",
                    models.BooleanField(default=True, verbose_name="Planejado?"),
                ),
                (
                    "identification",
                    models.CharField(
                        max_length=128, verbose_name="Identificação da Despesa"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "PERMANENT_GOODS_AND_MATERIALS",
                                "Bens e Materiais permanentes",
                            ),
                            (
                                "COMPUTER_GOODS_AND_EQUIPMENT",
                                "Bens e equipamentos de informática",
                            ),
                            (
                                "HOSPITAL_GOODS_AND_EQUIPMENT",
                                "Bens e equipamentos hospitalares",
                            ),
                            ("FUEL", "Combustível"),
                            ("BANKING_EXPENSES", "Despesas bancárias"),
                            ("BANKING_IOF", "IOF"),
                            ("BANKING_IRRF", "IRRF"),
                            ("INTEREST", "Juros"),
                            ("FOODSTUFFS", "Gêneros Alimentícios"),
                            ("REAL_ESTATE_LEASE", "Locação de Imóveis"),
                            ("AMBULANCES", "Ambulâncias"),
                            ("COMPUTER_EQUIPMENT", "Equipamento de informática"),
                            (
                                "HOSPITCAL_MEDICAL_EQUIPMENT",
                                "Equipamento médico hospitalar",
                            ),
                            ("LAUNDRY_LINEN", "Lavanderia e enxoval"),
                            ("CAR_LEASE", "Locação de Carro"),
                            ("MISCELLANOUS_LEASES", "Locações Diversas"),
                            ("SOFTWARE_SYSTEM", "Sistema de software"),
                            (
                                "MEDICAL_HOSPITAL_SUPPLIES",
                                "Material Médico e Hospitalar",
                            ),
                            ("MEDICINES", "Medicamentos"),
                            ("WORKS", "Obras"),
                            (
                                "OTHER_ADMINISTRATIVE_EXPENSES",
                                "Despesas Administrativas",
                            ),
                            (
                                "RETURN_OF_FUNDS",
                                "Devolução de Recurso ao Órgão Concedente",
                            ),
                            ("PARKING_DRIVING_TAXI", "Estacionamento/condução/táxi"),
                            ("IPTU", "IPTU"),
                            (
                                "TAXES_FEES_CONTRIBUTIONS",
                                "Impostos, Taxas e Contribuições",
                            ),
                            ("OTHER_EXPENSES", "Outras despesas - Diversos"),
                            ("INSURANCE", "Seguros"),
                            ("TRAVEL_TICKET_STAY", "Viagens (passagem, hospedagem)"),
                            ("COOKING_GAS", "Gás de Cozinha"),
                            ("COMPUTER_SUPPLIES", "Materiais de Informática"),
                            (
                                "MATERIALS_FOR_SMALL_REPAIRS",
                                "Materiais para Pequenos Reparos",
                            ),
                            ("EDUCATIONAL_MATERIAL", "Material Pedagógico"),
                            (
                                "HYGIENE_CLEANING_SUPPLIES_UNIFORMS",
                                "Material de Higiene/Limpeza/Uniformes",
                            ),
                            ("SPORTS_EQUIPMENTS", "Material esportivo"),
                            ("UTENSILS", "Utensílios"),
                            ("OFFICE_SUPPLIES_1", "Materiais de Expediente"),
                            ("OFFICE_SUPPLIES_2", "Material de Escritório"),
                            (
                                "OFFICE_SUPPLIES_3",
                                "Material de expediente/correio/fotocópias",
                            ),
                            ("OTHER_CONSUMABLES", "Outros Materiais de Consumo"),
                            ("COMMON_WASTE_COLLECT", "Coleta de lixo comum"),
                            ("HOSPITAL_WASTE_COLLECT", "Coleta de lixo hospitalar"),
                            (
                                "CONSULTING_LEGAL_ADVICE",
                                "Consultoria/assessoria jurídica",
                            ),
                            ("CLEANING_MAINTENANCE", "Limpeza e conservação"),
                            (
                                "MAINTENANCE_HOSPITAL_EQUIPMENT",
                                "Manutenção - Equipamento Médico Hospitalar",
                            ),
                            (
                                "MAINTENANCE_COMPUTER_EQUIPMENT",
                                "Manutenção - Equipamento de Informática",
                            ),
                            (
                                "MAINTENANCE_BUILDING",
                                "Manutenção - predial e Imobiliário",
                            ),
                            ("MAINTENANCE_VEHICLE", "Manutenção de veículos"),
                            ("CONSTRUCTION", "Obras"),
                            ("MAINTENANCE_OTHERS", "Outras Manutenções"),
                            (
                                "LEGAL_THIRD_PARTY_SERVICES",
                                "Outros serviços de terceiros pessoa jurídica",
                            ),
                            ("ADVERTISING_PUBILICITY", "Publicidade e propaganda"),
                            (
                                "THERAPEUTIC_SUPPORT_SERVICE",
                                "Serviço de apoio diagnóstico terapêutico (sadt)",
                            ),
                            ("SERVICES_ACCOUNTING", "Serviços Contábeis"),
                            ("SERVICES_AUDITING", "Serviços de auditoria"),
                            (
                                "SERVIECS_IT",
                                "Serviços de tecnologia da informação (TI)",
                            ),
                            ("SERVICES_SURVEILLANCES", "Vigilância"),
                            ("THIRTHEENTH_SALARY", "13º Salário"),
                            ("APPRENTICES", "Aprendizes"),
                            ("MEDICAL_ASSISTENCE", "Assistência médica"),
                            ("ADVANCE_NOTICE", "Aviso prévio"),
                            ("BENEFITS", "Benefícios"),
                            ("INTERNSHIP_ALLOWANCE", "Bolsa Auxílio - estagiários"),
                            (
                                "INSS_CONTRIBUTION_SHARE",
                                "Contribuição ao INSS - Cota Patronal",
                            ),
                            ("PIS_CONTRIBUTION", "Contribuição ao PIS"),
                            ("SOCIAL_CONTRIBUTIONS", "Contribuições Sociais"),
                            (
                                "COURSES_TRAINING_RETRAINING",
                                "Cursos/treinamento/reciclagem",
                            ),
                            ("PERSONNEL_EXPENSES", "Despesas com Pessoal"),
                            ("COLLECTIVE_BARGAINING", "Dissídio coletivo"),
                            ("SOCIAL_CHARGES", "Encargos Sociais"),
                            ("FGTS", "FGTS"),
                            ("RESERVE_FUND", "Fundo de Reserva"),
                            ("VACATIONS", "Férias"),
                            ("BONUSES", "Gratificações"),
                            ("HR_INSS", "INSS"),
                            ("HR_IRRF", "IRRF"),
                            ("COMPENSATIONS", "Indenizações"),
                            (
                                "TERMINATION_EMPLOYMENT_CONTRACT",
                                "Rescisão de Contrato de Trabalho - TRCT",
                            ),
                            ("MISCELLANOUS_WITHHOLDINGS", "Retenções Diversas"),
                            (
                                "MANAGEMENT_SALARY",
                                "Salário diretoria (salários e ordenados)",
                            ),
                            (
                                "SALARIES_AND_WAGES",
                                "Salários e ordenados (exceto diretoria)",
                            ),
                            ("UNIFORMS", "Uniformes"),
                            ("FOOD_VOUCHERS", "Vale Alimentação"),
                            ("MEAL_VOUCHERS", "Vale Refeição"),
                            ("TRANSPORTATION_VOUCHERS", "Vale Transporte"),
                            ("INTERN_REMUNERATION", "Remuneração de Estagiários"),
                            (
                                "SERVICES_PF_THIRD_PARTIES",
                                "Serviços Prestados por Terceiro - PF",
                            ),
                            (
                                "SERVICES_PJ_THIRD_PARTIES",
                                "Serviços Prestados por Terceiro - PJ",
                            ),
                            ("MEDICAL_SERVICES", "Serviços médicos (*)"),
                            (
                                "MEDICAL_SERVICES_FOR_INDIVIDUALS",
                                "Serviços médicos pessoa física",
                            ),
                            (
                                "MEDICAL_SERVICES_FOR_ENTITIES",
                                "Serviços médicos pessoa jurídica",
                            ),
                            (
                                "PUBLIC_ADMINISTRATIVE_EXPENSES",
                                "Despesas Administrativas",
                            ),
                            ("ELECTRICITY", "Energia Elétrica"),
                            ("INTERNET_TV", "Internet/TV a cabo"),
                            ("TELEPHONE", "Telefone"),
                            ("PUBLIC_UTILITIES", "Utilidade Publica"),
                            ("WATER_SEWAGE", "Água e Esgoto"),
                        ],
                        max_length=34,
                        null=True,
                        verbose_name="Natureza da Despesa",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Vencimento"),
                ),
                ("competency", models.DateField(verbose_name="Competência")),
                (
                    "liquidation",
                    models.DateField(blank=True, null=True, verbose_name="Liquidação"),
                ),
                (
                    "liquidation_form",
                    models.CharField(
                        choices=[
                            ("BILL", "Boleto"),
                            ("CHECK", "Cheque"),
                            ("DEBIT_CREDIT_CARD", "Cartão Débito/Crédito"),
                            ("DIRECT_DEBIT", "Débito em Conta"),
                            ("ELETRONIC_TRANSFER", "Transferência Eletrônica"),
                            ("MONEY", "Dinheiro"),
                            ("OBTV", "OBTV"),
                        ],
                        default="ELETRONIC_TRANSFER",
                        max_length=18,
                        verbose_name="Forma de Liquidação",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSURANCE_POLICY", "Apolice de Seguro"),
                            ("DEBIT_NOTICE", "Aviso de Débito"),
                            ("PAY_SLIP", "Boleto"),
                            ("TAX_RECEIPT", "Cupom Fiscal"),
                            ("DARF", "DARF"),
                            ("INVOICE", "Fatura"),
                            ("GPS", "GPS"),
                            ("GRCS_DOC", "GRCS ou DOC"),
                            ("GRF", "GRF"),
                            ("GRRF", "GRRF"),
                            ("PAYSLIP", "Holerite"),
                            ("NF", "NF"),
                            ("NFE", "NF-E"),
                            ("NFS", "NFS"),
                            ("NFSE", "NFS-E"),
                            (
                                "NF_INVOICES",
                                "Notas Fiscais (Eletronica, Serviços, etc)",
                            ),
                            ("OTHERS", "Outros"),
                            ("RECEIPT", "Recibo"),
                            ("VACATION_RECEIPT", "Recibo de Férias"),
                            ("RPA", "RPA"),
                            ("TERMINATION_AGREEMENT", "Termo de Rescisão"),
                        ],
                        max_length=21,
                        null=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Número do documento",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Despesa",
                "verbose_name_plural": "historical Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExpenseAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                (
                    "comments",
                    models.CharField(max_length=256, verbose_name="Comentários"),
                ),
                (
                    "pending",
                    models.CharField(max_length=256, verbose_name="Pendências"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Análise de Despesa",
                "verbose_name_plural": "historical Análise de Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExpenseFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Arquivo"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Arquivo de Despesa",
                "verbose_name_plural": "historical Arquivo de Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_ANALISIS", "Em Análise"),
                            ("REJECTED", "Rejeitada"),
                            ("APPROVED", "Aprovada"),
                        ],
                        default="IN_ANALISIS",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pendencies",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pendências"
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        max_length=128, verbose_name="Identificação da Despesa"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                ("competency", models.DateField(verbose_name="Competência")),
                (
                    "receive_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "revenue_nature",
                    models.CharField(
                        choices=[
                            ("UNDUE_CREDIT", "Crédito Indevido"),
                            ("BANK_DEPOSIT", "Depósito Bancário"),
                            (
                                "RETURN_DEPOSIT",
                                "Depósito para devolução ao Órgão Concedente",
                            ),
                            ("PAYMENT_REVERSAL", "Estorno de Pagamento"),
                            ("FEE_REVERSAL", "Estorno de Tarifas"),
                            (
                                "OTHER_REVENUES",
                                "Outras Receitas decorrentes da execução do ajuste",
                            ),
                            ("OWN_RESOURCES", "Recurso próprio da entidade parceira"),
                            (
                                "REIMBURSEMENT_INTEREST",
                                "Reembolso de Juros, multas, glosas, pagto. Indevido, duplicidade etc",
                            ),
                            ("FEE_REIMBURSEMENT", "Reembolso de Tarifas"),
                            ("INVESTMENT_INCOME", "Rendimento de Aplicação"),
                            ("SAVINGS_INCOME", "Rendimento de Poupança"),
                            ("PUBLIC_TRANSFER", "Repasse Público"),
                            ("PREVIOUS_BALANCE", "Saldo anterior para acerto"),
                        ],
                        default="BANK_DEPOSIT",
                        max_length=22,
                        verbose_name="Natureza da Receita",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receita",
                "verbose_name_plural": "historical Receitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevenueFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Arquivo de Receita",
                "verbose_name_plural": "historical Arquivo de Receitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ResourceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nome da fonte")),
                (
                    "document",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="CPF/CNPJ da fonte"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Número do contrato",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("FEDERAL", "Federal"),
                            ("STATE", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                            ("PRIVATE_SPONSOR", "Patrocinador privado"),
                        ],
                        default="FEDERAL",
                        max_length=19,
                        verbose_name="Origem da Fonte",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NOT_APPLIABLE", "Não Aplicavél"),
                            ("COOPERATION_AGREEMENT", "Acordo de Cooperação"),
                            ("AGREEMENT", "Convênio"),
                            ("COLLABORATION_AGREEMENT", "Termo de Colaboração"),
                            ("PROMOTION_AGREEMENT", "Termo de Fomento"),
                            ("DONATION_AGREEMENT", "Contrato de Doação"),
                            ("MANAGEMENT_AGREEMENT", "Contrato de Gestão"),
                            ("TRANSFER_AGREEMENT", "Contrato de Repasse"),
                            ("PARTNERSHIP_AGREEMENT", "Termo de Parceria"),
                        ],
                        default="NOT_APPLIABLE",
                        max_length=23,
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonte de Recurso",
                "verbose_name_plural": "Fonte de Recursos",
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_ANALISIS", "Em Análise"),
                            ("REJECTED", "Rejeitada"),
                            ("APPROVED", "Aprovada"),
                        ],
                        default="IN_ANALISIS",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pendencies",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pendências"
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        max_length=128, verbose_name="Identificação da Despesa"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                ("competency", models.DateField(verbose_name="Competência")),
                (
                    "receive_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "revenue_nature",
                    models.CharField(
                        choices=[
                            ("UNDUE_CREDIT", "Crédito Indevido"),
                            ("BANK_DEPOSIT", "Depósito Bancário"),
                            (
                                "RETURN_DEPOSIT",
                                "Depósito para devolução ao Órgão Concedente",
                            ),
                            ("PAYMENT_REVERSAL", "Estorno de Pagamento"),
                            ("FEE_REVERSAL", "Estorno de Tarifas"),
                            (
                                "OTHER_REVENUES",
                                "Outras Receitas decorrentes da execução do ajuste",
                            ),
                            ("OWN_RESOURCES", "Recurso próprio da entidade parceira"),
                            (
                                "REIMBURSEMENT_INTEREST",
                                "Reembolso de Juros, multas, glosas, pagto. Indevido, duplicidade etc",
                            ),
                            ("FEE_REIMBURSEMENT", "Reembolso de Tarifas"),
                            ("INVESTMENT_INCOME", "Rendimento de Aplicação"),
                            ("SAVINGS_INCOME", "Rendimento de Poupança"),
                            ("PUBLIC_TRANSFER", "Repasse Público"),
                            ("PREVIOUS_BALANCE", "Saldo anterior para acerto"),
                        ],
                        default="BANK_DEPOSIT",
                        max_length=22,
                        verbose_name="Natureza da Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
            },
        ),
        migrations.CreateModel(
            name="RevenueFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/revenues/",
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Receita",
                "verbose_name_plural": "Arquivo de Receitas",
            },
        ),
    ]
