# Generated by Django 5.1.4 on 2024-12-24 15:54

import django.db.models.fields
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accountability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
            },
        ),
        migrations.CreateModel(
            name="AccountabilityFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "reconciled",
                    models.BooleanField(default=False, verbose_name="Conciliado"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
        migrations.CreateModel(
            name="ExpenseAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                (
                    "comments",
                    models.CharField(max_length=256, verbose_name="Comentários"),
                ),
                (
                    "pending",
                    models.CharField(max_length=256, verbose_name="Pendências"),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAccountability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "janeiro"),
                            (2, "fevereiro"),
                            (3, "março"),
                            (4, "abril"),
                            (5, "maio"),
                            (6, "junho"),
                            (7, "julho"),
                            (8, "agosto"),
                            (9, "setembro"),
                            (10, "outubro"),
                            (11, "novembro"),
                            (12, "dezembro"),
                        ],
                        default=1,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Relatório",
                "verbose_name_plural": "historical Relatórios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAccountabilityFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receita",
                "verbose_name_plural": "historical Receitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "reconciled",
                    models.BooleanField(default=False, verbose_name="Conciliado"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Despesa",
                "verbose_name_plural": "historical Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExpenseAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "em análise"),
                            ("CORRECTING", "correção"),
                            ("APPROVED", "aprovado"),
                            ("APPROVED_WITH_PENDENCE", "aprovado com ressalva"),
                            ("REJECTED", "rejeitado"),
                        ],
                        default="ANALYZING",
                        max_length=22,
                        verbose_name="Status",
                    ),
                ),
                (
                    "comments",
                    models.CharField(max_length=256, verbose_name="Comentários"),
                ),
                (
                    "pending",
                    models.CharField(max_length=256, verbose_name="Pendências"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Despesa",
                "verbose_name_plural": "historical Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Receita",
                "verbose_name_plural": "historical Receitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Despesa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
            },
        ),
    ]
