# Generated by Django 6.0.5 on 2026-05-14 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountability', '0001_initial'),
        ('accounts', '0001_initial'),
        ('bank', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountability',
            name='committee_member',
            field=models.ForeignKey(blank=True, help_text='Membro do comitê que será notificado quando a prestação for aprovada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Membro do Comitê para Notificação'),
        ),
        migrations.AddField(
            model_name='accountability',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountabilities', to='contracts.contract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='accountability',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='accountability',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Análise'),
        ),
        migrations.AddField(
            model_name='accountabilityfile',
            name='accountability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accountability.accountability', verbose_name='Prestação'),
        ),
        migrations.AddField(
            model_name='accountabilityfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_files', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='accountabilityfile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='expense',
            name='accountability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accountability.accountability', verbose_name='Prestação'),
        ),
        migrations.AddField(
            model_name='expense',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='contracts.contractitem', verbose_name='Item Relacionado'),
        ),
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='expensefile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_files', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='expensefile',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accountability.expense', verbose_name='Despesa'),
        ),
        migrations.AddField(
            model_name='expensefile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='favored',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='expense',
            name='favored',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accountability.favored', verbose_name='Favorecido'),
        ),
        migrations.AddField(
            model_name='historicalaccountability',
            name='committee_member',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Membro do comitê que será notificado quando a prestação for aprovada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Membro do Comitê para Notificação'),
        ),
        migrations.AddField(
            model_name='historicalaccountability',
            name='contract',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalaccountability',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccountability',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalaccountability',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Análise'),
        ),
        migrations.AddField(
            model_name='historicalaccountabilityfile',
            name='accountability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.accountability', verbose_name='Prestação'),
        ),
        migrations.AddField(
            model_name='historicalaccountabilityfile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalaccountabilityfile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccountabilityfile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='accountability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.accountability', verbose_name='Prestação'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='favored',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.favored', verbose_name='Favorecido'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contractitem', verbose_name='Item Relacionado'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalexpensefile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalexpensefile',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.expense', verbose_name='Despesa'),
        ),
        migrations.AddField(
            model_name='historicalexpensefile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpensefile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalrevenue',
            name='accountability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.accountability', verbose_name='Contabilidade'),
        ),
        migrations.AddField(
            model_name='historicalrevenue',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank.bankaccount', verbose_name='Conta Bancária Destino'),
        ),
        migrations.AddField(
            model_name='historicalrevenue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrevenue',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalrevenuefile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalrevenuefile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrevenuefile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='resourcesource',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.resourcesource', verbose_name='Fonte de Despesa'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accountability.resourcesource', verbose_name='Fonte de Despesa'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='accountability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='accountability.accountability', verbose_name='Contabilidade'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='bank.bankaccount', verbose_name='Conta Bancária Destino'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalrevenuefile',
            name='revenue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountability.revenue', verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='revenuefile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_files', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='revenuefile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization associated with this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='revenuefile',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accountability.revenue', verbose_name='Recurso'),
        ),
        migrations.AlterUniqueTogether(
            name='accountability',
            unique_together={('contract', 'month', 'year')},
        ),
        migrations.AddConstraint(
            model_name='favored',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'document'), name='unique_favored_document_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='resourcesource',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'document'), name='unique_resource_source_document_per_organization'),
        ),
    ]
