# Generated by Django 5.1.4 on 2024-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenseanalysis",
            options={
                "verbose_name": "Análise de Despesa",
                "verbose_name_plural": "Análise de Despesas",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalexpenseanalysis",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Análise de Despesa",
                "verbose_name_plural": "historical Análise de Despesas",
            },
        ),
        migrations.AddField(
            model_name="accountability",
            name="year",
            field=models.IntegerField(default=0, verbose_name="Ano"),
        ),
        migrations.AddField(
            model_name="historicalaccountability",
            name="year",
            field=models.IntegerField(default=0, verbose_name="Ano"),
        ),
        migrations.AlterUniqueTogether(
            name="accountability",
            unique_together={("month", "year")},
        ),
    ]
