# Generated by Django 5.1.6 on 2025-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favored",
            name="document",
            field=models.CharField(blank=True, null=True, verbose_name="CPF/CNPJ"),
        ),
    ]
