# Generated by Django 5.1.4 on 2025-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountability",
            name="status",
            field=models.CharField(
                choices=[
                    ("WIP", "Em "),
                    ("SENT", "Enviada para análise"),
                    ("REJECTED", "Rejeitada"),
                    ("PENDENCIES", "Com pendências"),
                    ("APPROVED", "Aprovada"),
                    ("FINISHED", "Finalizada"),
                ],
                default="WIP",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccountability",
            name="status",
            field=models.CharField(
                choices=[
                    ("WIP", "Em "),
                    ("SENT", "Enviada para análise"),
                    ("REJECTED", "Rejeitada"),
                    ("PENDENCIES", "Com pendências"),
                    ("APPROVED", "Aprovada"),
                    ("FINISHED", "Finalizada"),
                ],
                default="WIP",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
