# Generated by Django 5.1.4 on 2025-01-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0003_favored_organization"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accountability.expensesource",
                verbose_name="Fonte de Despesa",
            ),
        ),
        migrations.AlterField(
            model_name="favored",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoreds",
                to="accounts.organization",
                verbose_name="Organização",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.expensesource",
                verbose_name="Fonte de Despesa",
            ),
        ),
    ]
