# Generated by Django 5.1.6 on 2025-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0003_alter_favored_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrevenue",
            name="conciled",
            field=models.BooleanField(
                default=False, verbose_name="Conciliado?"
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Pago?"),
        ),
        migrations.AddField(
            model_name="revenue",
            name="conciled",
            field=models.BooleanField(
                default=False, verbose_name="Conciliado?"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Pago?"),
        ),
    ]
