# Generated by Django 5.1.4 on 2025-02-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0003_alter_resourcesource_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
    ]
