# Generated by Django 5.1.4 on 2024-12-30 17:56

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0003_alter_expenseanalysis_options_and_more"),
        ("accounts", "0007_area_city_hall_historicalarea_city_hall"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nome da fonte")),
                (
                    "document",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="CPF/CNPJ da fonte"
                    ),
                ),
                (
                    "city_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_sources",
                        to="accounts.cityhall",
                        verbose_name="Prefeitura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonte de Gasto",
                "verbose_name_plural": "Fonte de Gastos",
                "unique_together": {("city_hall", "name")},
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accountability.expensesource",
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.expensesource",
                verbose_name="source",
            ),
        ),
        migrations.CreateModel(
            name="RevenueSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nome da fonte")),
                (
                    "document",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="CPF/CNPJ da fonte"
                    ),
                ),
                (
                    "city_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_sources",
                        to="accounts.cityhall",
                        verbose_name="Prefeitura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonte de Receita",
                "verbose_name_plural": "Fonte de Receitas",
                "unique_together": {("city_hall", "name")},
            },
        ),
    ]
