# Generated by Django 6.0.5 on 2026-07-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0003_expense_apportionment_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="encumbrance_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deve ser informado como zero quando não houver retenção",
                max_digits=12,
                null=True,
                verbose_name="Valor de Encargos Retidos",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="encumbrance_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deve ser informado como zero quando não houver retenção",
                max_digits=12,
                null=True,
                verbose_name="Valor de Encargos Retidos",
            ),
        ),
    ]
