# Generated by Django 6.0.5 on 2026-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0004_expense_encumbrance_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="issuing_state",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Código AUDESP (1-27) — tabela de referência pendente",
                null=True,
                verbose_name="Estado Emissor do Documento Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="fundtransfer",
            name="bank",
            field=models.PositiveIntegerField(
                help_text="Código do banco (tabela BACEN) — tabela de referência pendente",
                verbose_name="Banco",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="issuing_state",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Código AUDESP (1-27) — tabela de referência pendente",
                null=True,
                verbose_name="Estado Emissor do Documento Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfundtransfer",
            name="bank",
            field=models.PositiveIntegerField(
                help_text="Código do banco (tabela BACEN) — tabela de referência pendente",
                verbose_name="Banco",
            ),
        ),
    ]
