# Generated by Django 5.1.4 on 2025-01-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0004_favored_remove_expense_reconciled_and_more"),
        ("bank", "0004_alter_bankstatement_opening_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrevenue",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bank.bankaccount",
                verbose_name="Conta Bancária Destino",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="competency",
            field=models.DateField(blank=True, null=True, verbose_name="Competência"),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="identification",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Identificação da Despesa",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="revenue_nature",
            field=models.CharField(
                choices=[
                    ("UNDUE_CREDIT", "Crédito Indevido"),
                    ("BANK_DEPOSIT", "Depósito Bancário"),
                    ("RETURN_DEPOSIT", "Depósito para devolução ao Órgão Concedente"),
                    ("PAYMENT_REVERSAL", "Estorno de Pagamento"),
                    ("FEE_REVERSAL", "Estorno de Tarifas"),
                    (
                        "OTHER_REVENUES",
                        "Outras Receitas decorrentes da execução do ajuste",
                    ),
                    ("OWN_RESOURCES", "Recurso próprio da entidade parceira"),
                    (
                        "REIMBURSEMENT_INTEREST",
                        "Reembolso de Juros, multas, glosas, pagto. Indevido, duplicidade etc",
                    ),
                    ("FEE_REIMBURSEMENT", "Reembolso de Tarifas"),
                    ("INVESTMENT_INCOME", "Rendimento de Aplicação"),
                    ("SAVINGS_INCOME", "Rendimento de Poupança"),
                    ("PUBLIC_TRANSFER", "Repasse Público"),
                    ("PREVIOUS_BALANCE", "Saldo anterior para acerto"),
                ],
                default="BANK_DEPOSIT",
                max_length=22,
                verbose_name="Natureza da Receita",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="revenue_source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.revenuesource",
                verbose_name="Fonte de Recurso",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenues",
                to="bank.bankaccount",
                verbose_name="Conta Bancária Destino",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="competency",
            field=models.DateField(blank=True, null=True, verbose_name="Competência"),
        ),
        migrations.AddField(
            model_name="revenue",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
        migrations.AddField(
            model_name="revenue",
            name="identification",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Identificação da Despesa",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="observations",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="revenue_nature",
            field=models.CharField(
                choices=[
                    ("UNDUE_CREDIT", "Crédito Indevido"),
                    ("BANK_DEPOSIT", "Depósito Bancário"),
                    ("RETURN_DEPOSIT", "Depósito para devolução ao Órgão Concedente"),
                    ("PAYMENT_REVERSAL", "Estorno de Pagamento"),
                    ("FEE_REVERSAL", "Estorno de Tarifas"),
                    (
                        "OTHER_REVENUES",
                        "Outras Receitas decorrentes da execução do ajuste",
                    ),
                    ("OWN_RESOURCES", "Recurso próprio da entidade parceira"),
                    (
                        "REIMBURSEMENT_INTEREST",
                        "Reembolso de Juros, multas, glosas, pagto. Indevido, duplicidade etc",
                    ),
                    ("FEE_REIMBURSEMENT", "Reembolso de Tarifas"),
                    ("INVESTMENT_INCOME", "Rendimento de Aplicação"),
                    ("SAVINGS_INCOME", "Rendimento de Poupança"),
                    ("PUBLIC_TRANSFER", "Repasse Público"),
                    ("PREVIOUS_BALANCE", "Saldo anterior para acerto"),
                ],
                default="BANK_DEPOSIT",
                max_length=22,
                verbose_name="Natureza da Receita",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="revenue_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenues",
                to="accountability.revenuesource",
                verbose_name="Fonte de Recurso",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="liquidation_form",
            field=models.CharField(
                choices=[
                    ("BILL", "Boleto"),
                    ("CHECK", "Cheque"),
                    ("DEBIT_CREDIT_CARD", "Cartão Débito/Crédito"),
                    ("DIRECT_DEBIT", "Débito em Conta"),
                    ("ELETRONIC_TRANSFER", "Transferência Eletrônica"),
                    ("MONEY", "Dinheiro"),
                    ("OBTV", "OBTV"),
                ],
                default="ELETRONIC_TRANSFER",
                max_length=18,
                verbose_name="Forma de Liquidação",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="liquidation_form",
            field=models.CharField(
                choices=[
                    ("BILL", "Boleto"),
                    ("CHECK", "Cheque"),
                    ("DEBIT_CREDIT_CARD", "Cartão Débito/Crédito"),
                    ("DIRECT_DEBIT", "Débito em Conta"),
                    ("ELETRONIC_TRANSFER", "Transferência Eletrônica"),
                    ("MONEY", "Dinheiro"),
                    ("OBTV", "OBTV"),
                ],
                default="ELETRONIC_TRANSFER",
                max_length=18,
                verbose_name="Forma de Liquidação",
            ),
        ),
    ]
