# Generated by Django 5.1.6 on 2025-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountability",
            "0004_historicalrevenue_conciled_historicalrevenue_paid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrevenue",
            name="source",
            field=models.CharField(
                choices=[("CITY_HALL", "Prefeitura"), ("COUNTERPART", "Contrapartida")],
                default="CITY_HALL",
                verbose_name="Fonte de Recurso",
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="source",
            field=models.CharField(
                choices=[("CITY_HALL", "Prefeitura"), ("COUNTERPART", "Contrapartida")],
                default="CITY_HALL",
                verbose_name="Fonte de Recurso",
            ),
        ),
    ]
