# Generated by Django 5.1.4 on 2025-01-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0004_expensesource_expense_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensesource",
            options={
                "verbose_name": "Fonte de Despesa",
                "verbose_name_plural": "Fonte de Despesas",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrevenue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Recurso",
                "verbose_name_plural": "historical Recursos",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={"verbose_name": "Recurso", "verbose_name_plural": "Recursos"},
        ),
        migrations.AlterModelOptions(
            name="revenuesource",
            options={
                "verbose_name": "Fonte de Recurso",
                "verbose_name_plural": "Fonte de Recursos",
            },
        ),
        migrations.AlterField(
            model_name="accountabilityfile",
            name="revenue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountabilitie_files",
                to="accountability.revenue",
                verbose_name="Recurso",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accountability.expensesource",
                verbose_name="Fonte",
            ),
        ),
        migrations.AlterField(
            model_name="expenseanalysis",
            name="reviwer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_anaysis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccountabilityfile",
            name="revenue",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.revenue",
                verbose_name="Recurso",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.expensesource",
                verbose_name="Fonte",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrevenue",
            name="accountability",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.accountability",
                verbose_name="Contabilidade",
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="accountability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenues",
                to="accountability.accountability",
                verbose_name="Contabilidade",
            ),
        ),
    ]
