# Generated by Django 6.0.5 on 2026-08-14 20:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_accountability(apps, schema_editor):
    ExpenseFile = apps.get_model("accountability", "ExpenseFile")
    HistoricalExpenseFile = apps.get_model("accountability", "HistoricalExpenseFile")

    for document in ExpenseFile.objects.filter(expense__isnull=False).iterator():
        document.accountability_id = document.expense.accountability_id
        document.save(update_fields=["accountability"])

    for document in HistoricalExpenseFile.objects.filter(
        expense__isnull=False
    ).iterator():
        document.accountability_id = document.expense.accountability_id
        document.save(update_fields=["accountability"])


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0004_expense_encumbrance_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensefile",
            name="accountability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_documents",
                to="accountability.accountability",
                verbose_name="Prestação",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpensefile",
            name="accountability",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.accountability",
                verbose_name="Prestação",
            ),
        ),
        migrations.AlterField(
            model_name="expensefile",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="accountability.expense",
                verbose_name="Despesa",
            ),
        ),
        migrations.RunPython(backfill_accountability, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="expensefile",
            name="accountability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_documents",
                to="accountability.accountability",
                verbose_name="Prestação",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpensefile",
            name="accountability",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.accountability",
                verbose_name="Prestação",
            ),
        ),
    ]
