# Generated by Django 5.1.4 on 2025-02-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0004_expense_due_date_historicalexpense_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="favored",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="accountability.favored",
                verbose_name="Favorecido",
            ),
        ),
    ]
