# Generated by Django 5.1.4 on 2025-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0005_alter_expensesource_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenuesource",
            name="category",
            field=models.CharField(
                choices=[
                    ("NOT_APPLIABLE", "Não Aplicavél"),
                    ("COOPERATION_AGREEMENT", "Acordo de Cooperação"),
                    ("AGREEMENT", "Convênio"),
                    ("COLLABORATION_AGREEMENT", "Termo de Colaboração"),
                    ("PROMOTION_AGREEMENT", "Termo de Fomento"),
                    ("DONATION_AGREEMENT", "Contrato de Doação"),
                    ("MANAGEMENT_AGREEMENT", "Contrato de Gestão"),
                    ("TRANSFER_AGREEMENT", "Contrato de Repasse"),
                    ("PARTNERSHIP_AGREEMENT", "Termo de Parceria"),
                ],
                default="NOT_APPLIABLE",
                max_length=23,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="revenuesource",
            name="origin",
            field=models.CharField(
                choices=[
                    ("FEDERAL", "Federal"),
                    ("STATE", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                    ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                    ("PRIVATE_SPONSOR", "Patrocinador privado"),
                ],
                default="FEDERAL",
                max_length=19,
                verbose_name="Origem da Fonte",
            ),
        ),
    ]
