# Generated by Django 5.1.4 on 2025-02-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0005_alter_expense_nature_alter_historicalexpense_nature"),
        ("accounts", "0004_user_cpf"),
    ]

    operations = [
        migrations.RenameModel(old_name="RevenueSource", new_name="ResourceSource",),
    ]
