# Generated by Django 5.1.6 on 2025-03-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accountability",
            "0005_alter_historicalrevenue_source_alter_revenue_source",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="favored",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Nome"),
        ),
    ]
