# Generated by Django 5.1.4 on 2025-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0005_alter_expense_favored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountability",
            name="status",
            field=models.CharField(
                choices=[
                    ("WIP", "Em Andamento"),
                    ("SENT", "Enviada para análise"),
                    ("CORRECTING", "Corrigindo"),
                    ("FINISHED", "Finalizada"),
                ],
                default="WIP",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccountability",
            name="status",
            field=models.CharField(
                choices=[
                    ("WIP", "Em Andamento"),
                    ("SENT", "Enviada para análise"),
                    ("CORRECTING", "Corrigindo"),
                    ("FINISHED", "Finalizada"),
                ],
                default="WIP",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
