# Generated by Django 5.1.4 on 2025-01-24 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0005_historicalrevenue_bank_account_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expensesource", unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="revenuesource", unique_together={("organization", "name")},
        ),
        migrations.AddField(
            model_name="expensesource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_sources",
                to="accounts.organization",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="revenuesource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenue_sources",
                to="accounts.organization",
                verbose_name="Organização",
            ),
        ),
        migrations.RemoveField(model_name="expensesource", name="city_hall",),
        migrations.RemoveField(model_name="revenuesource", name="city_hall",),
    ]
