# Generated by Django 5.1.6 on 2025-03-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0006_alter_favored_name"),
        ("bank", "0005_remove_transaction_unique__transaction_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="bank.transaction",
                verbose_name="Transação",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bank.transaction",
                verbose_name="Transação",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bank.transaction",
                verbose_name="Transação",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenues",
                to="bank.transaction",
                verbose_name="Transação",
            ),
        ),
    ]
