# Generated by Django 6.0.5 on 2026-08-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_alter_expense_issuing_state_alter_fundtransfer_bank_and_more'),
        ('accountability', '0006_alter_accountabilityfile_created_by_and_more'),
    ]

    operations = [
    ]
