# Generated by Django 5.1.4 on 2025-02-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0006_rename_revenuesource_resourcesource"),
        ("accounts", "0004_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accountability.resourcesource",
                verbose_name="Fonte de Despesa",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accountability.resourcesource",
                verbose_name="Fonte de Despesa",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesource",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_source",
                to="accounts.organization",
                verbose_name="Organização",
            ),
        ),
        migrations.DeleteModel(name="ExpenseSource",),
    ]
