# Generated by Django 5.1.6 on 2025-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountability",
            "0007_expense_transaction_historicalexpense_transaction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="expense", name="transaction",),
        migrations.RemoveField(model_name="historicalexpense", name="transaction",),
        migrations.RemoveField(model_name="historicalrevenue", name="transaction",),
        migrations.RemoveField(model_name="revenue", name="transaction",),
    ]
