# Generated by Django 5.1.4 on 2025-02-07 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0007_alter_accountability_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrevenue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Revenue",
                "verbose_name_plural": "historical Revenues",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={"verbose_name": "Revenue", "verbose_name_plural": "Revenues"},
        ),
    ]
