# Generated by Django 5.1.6 on 2025-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0008_remove_expense_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcesource",
            name="origin",
            field=models.CharField(
                choices=[
                    ("FEDERAL", "Federal"),
                    ("STATE", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                    ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                    ("PRIVATE_SPONSOR", "Patrocinador privado"),
                    ("PARLIAMENTARY", "Emenda Parlamentar"),
                ],
                default="FEDERAL",
                max_length=19,
                verbose_name="Origem da Fonte",
            ),
        ),
    ]
