# Generated by Django 5.1.4 on 2025-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0008_alter_historicalrevenue_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrevenue",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="revenue",
            name="due_date",
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="receive_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Recebimento"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="receive_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Recebimento"
            ),
        ),
    ]
