# Generated by Django 5.1.4 on 2025-02-07 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0009_remove_historicalrevenue_due_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountability",
            options={"verbose_name": "Prestação", "verbose_name_plural": "Prestações"},
        ),
        migrations.AlterModelOptions(
            name="historicalaccountability",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Prestação",
                "verbose_name_plural": "historical Prestações",
            },
        ),
    ]
