# Generated by Django 5.1.4 on 2025-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0010_alter_accountability_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_ANALISIS", "Em Análise"),
                    ("REJECTED", "Rejeitada"),
                    ("APPROVED", "Aprovada"),
                ],
                default="IN_ANALISIS",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_ANALISIS", "Em Análise"),
                    ("REJECTED", "Rejeitada"),
                    ("APPROVED", "Aprovada"),
                ],
                default="IN_ANALISIS",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_ANALISIS", "Em Análise"),
                    ("REJECTED", "Rejeitada"),
                    ("APPROVED", "Aprovada"),
                ],
                default="IN_ANALISIS",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_ANALISIS", "Em Análise"),
                    ("REJECTED", "Rejeitada"),
                    ("APPROVED", "Aprovada"),
                ],
                default="IN_ANALISIS",
                max_length=11,
                verbose_name="Status",
            ),
        ),
    ]
