# Generated by Django 5.1.4 on 2025-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountability", "0011_expense_status_historicalexpense_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências"
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências"
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenue",
            name="pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="pendencies",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pendências"
            ),
        ),
    ]
