# Generated by Django 5.1.6 on 2025-03-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0012_accountability_organization_and_more"),
        ("accounts", "0008_delete_organizationtenantbaseclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountability",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="accountabilityfile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="expenseanalysis",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="expensefile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="favored",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccountability",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccountabilityfile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpenseanalysis",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpensefile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrevenue",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrevenuefile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="revenuefile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization associated with this tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="accounts.organization",
            ),
        ),
    ]
