# Generated by Django 5.1.4 on 2025-02-08 21:06

import django.db.models.deletion
import django.db.models.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountability",
            "0012_expense_pendencies_historicalexpense_pendencies_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalaccountabilityfile", name="expense",
        ),
        migrations.RemoveField(
            model_name="historicalaccountabilityfile", name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalaccountabilityfile", name="revenue",
        ),
        migrations.AlterModelOptions(
            name="historicalrevenue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Receita",
                "verbose_name_plural": "historical Receitas",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={"verbose_name": "Receita", "verbose_name_plural": "Receitas"},
        ),
        migrations.CreateModel(
            name="ExpenseFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_files",
                        to="accountability.expense",
                        verbose_name="Despesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Despesa",
                "verbose_name_plural": "Arquivo de Despesas",
            },
        ),
        migrations.CreateModel(
            name="HistoricalExpenseFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.expense",
                        verbose_name="Despesa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Arquivo de Despesa",
                "verbose_name_plural": "historical Arquivo de Despesas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevenueFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revenue",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accountability.revenue",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Arquivo de Receita",
                "verbose_name_plural": "historical Arquivo de Receitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RevenueFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name=django.db.models.fields.UUIDField,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Tipo de Anexo"),
                ),
                (
                    "revenue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_files",
                        to="accountability.revenue",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Receita",
                "verbose_name_plural": "Arquivo de Receitas",
            },
        ),
        migrations.DeleteModel(name="AccountabilityFile",),
        migrations.DeleteModel(name="HistoricalAccountabilityFile",),
    ]
