# Generated by Django 5.1.6 on 2025-03-22 23:14

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0014_handle_duplicate_favoreds"),
        (
            "accounts",
            "0011_alter_user_options_alter_cityhall_document_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcesource",
            options={
                "verbose_name": "Fonte de Recursos",
                "verbose_name_plural": "Fontes de Recursos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="resourcesource",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="favored",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CPF ou CNPJ do favorecido",
                null=True,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="CPF/CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesource",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CPF ou CNPJ da fonte de recursos",
                null=True,
                validators=[utils.validators.validate_cpf_cnpj],
                verbose_name="CPF/CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesource",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="resourcesource",
            name="origin",
            field=models.CharField(
                choices=[
                    ("FEDERAL", "Federal"),
                    ("STATE", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                    ("COUNTERPART_PARTNER", "Contrapartida de parceiro"),
                    ("PRIVATE_SPONSOR", "Patrocinador privado"),
                    ("PARLIAMENTARY", "Emenda Parlamentar"),
                ],
                default="MUNICIPAL",
                max_length=19,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favored",
            unique_together={("organization", "document")},
        ),
        migrations.AlterUniqueTogether(
            name="resourcesource",
            unique_together={("organization", "document")},
        ),
    ]
