# Generated by Django 5.1.4 on 2025-02-09 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0014_expensefile_file_historicalexpensefile_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensefile",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalexpensefile",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalrevenuefile",
            name="category",
        ),
        migrations.RemoveField(
            model_name="revenuefile",
            name="category",
        ),
        migrations.AddField(
            model_name="expensefile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expense_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="expensefile",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Arquivo"
            ),
        ),
        migrations.AddField(
            model_name="historicalexpensefile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpensefile",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Arquivo"
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenuefile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="historicalrevenuefile",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Arquivo"
            ),
        ),
        migrations.AddField(
            model_name="revenuefile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenue_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="revenuefile",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nome do Arquivo"
            ),
        ),
    ]
