# Generated by Django 5.1.6 on 2025-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0015_alter_resourcesource_options_and_more"),
        ("accounts", "0012_alter_cityhall_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favored",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="resourcesource",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="favored",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "document"),
                name="unique_favored_document_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcesource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "document"),
                name="unique_resource_source_document_per_organization",
            ),
        ),
    ]
