# Generated by Django 5.1.6 on 2025-03-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0017_remove_historicalexpenseanalysis_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrevenue',
            name='conciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Liquidação'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='conciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Liquidação'),
        ),
    ]
