# Generated by Django 5.1.6 on 2025-09-15 14:31

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0020_alter_accountability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favored',
            name='document',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do favorecido', max_length=255, null=True, validators=[utils.validators.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='historicalrevenue',
            name='source',
            field=models.CharField(choices=[('CITY_HALL', 'Prefeitura'), ('COUNTERPART', 'Contrapartida')], default='CITY_HALL', max_length=255, verbose_name='Fonte de Recurso'),
        ),
        migrations.AlterField(
            model_name='resourcesource',
            name='document',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ da fonte de recursos', max_length=255, null=True, validators=[utils.validators.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='source',
            field=models.CharField(choices=[('CITY_HALL', 'Prefeitura'), ('COUNTERPART', 'Contrapartida')], default='CITY_HALL', max_length=255, verbose_name='Fonte de Recurso'),
        ),
    ]
