# Generated by Django 5.1.6 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0022_accountability_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountability',
            name='pendencies',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='observations',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicalaccountability',
            name='pendencies',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='observations',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Observações'),
        ),
    ]
