# Generated by Django 5.1.6 on 2025-09-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0024_accountability_committee_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountability',
            name='pendencies',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='pendencies',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('IN_ANALISIS', 'Em Análise'), ('UPDATED', 'Atualizada'), ('REJECTED', 'Rejeitada'), ('APPROVED', 'Aprovada')], default='IN_ANALISIS', max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalaccountability',
            name='pendencies',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='pendencies',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Pendências'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='status',
            field=models.CharField(choices=[('IN_ANALISIS', 'Em Análise'), ('UPDATED', 'Atualizada'), ('REJECTED', 'Rejeitada'), ('APPROVED', 'Aprovada')], default='IN_ANALISIS', max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalrevenue',
            name='status',
            field=models.CharField(choices=[('IN_ANALISIS', 'Em Análise'), ('UPDATED', 'Atualizada'), ('REJECTED', 'Rejeitada'), ('APPROVED', 'Aprovada')], default='IN_ANALISIS', max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='status',
            field=models.CharField(choices=[('IN_ANALISIS', 'Em Análise'), ('UPDATED', 'Atualizada'), ('REJECTED', 'Rejeitada'), ('APPROVED', 'Aprovada')], default='IN_ANALISIS', max_length=11, verbose_name='Status'),
        ),
    ]
